### ISSUE TITLE
Fails to retrieve version info for namespaced packages

### ISSUE THREAD

**Issue by FraserKillip** [vscode-contrib/vscode-versionlens#10]
The version information is blank for any package that uses a namespace, for example "@angular/core"
<img width="473" alt="screen shot 2016-07-10 at 1 49 14 pm" src="https://cloud.githubusercontent.com/assets/913951/16711248/472eecf6-46a5-11e6-96d2-662787cbafcf.png">

**Comment by WebFreak001** [comment]
Hm it works for me, maybe it only lagged a bit? They are only blank when they are loading. When they are finished it either says there was an error or it will tell you the version

**Comment by pflannery** [comment]
It seems that problem is scoped packages which isn't implemented in versionlens yet.

Will need to handle the @ sign in url encoding and there is an [issue](https://github.com/npm/registry/issues/34#issuecomment-231594567) using the `latest` keyword for scoped packages but can use `*` instead

**Comment by WebFreak001** [comment]
@pflannery but the bower API already handles that? It even works for me without any problem.

**Comment by pflannery** [comment]
@WebFreak001 I'm seeing this issue with npm. Have a fix coming shortly

**Comment by FraserKillip** [comment]
Awesome, thanks!

**Comment by pflannery** [comment]
@FraserKillip @WebFreak001 The fix is now available in 0.5.0. thanks

**Comment by pflannery** [comment]
Hit a light snag where using `*` instead of `latest` will pull in beta versions so have amended this fix to only use `*` for scoped packages until this is fixed https://github.com/npm/registry/issues/34#issuecomment-231594567
