### ISSUE TITLE
Unable to retrieve package information from internal bower registry

### ISSUE THREAD

**Issue by willpracht** [vscode-contrib/vscode-versionlens#102]
**What**

I'm receiving the `An error occurred retrieving this package` error in my `bower.json`.

**Details**

I have a `.bowerrc` located in my home folder:

```js
{
  "registry": {
    "search": [
      "url-to-my-internal-bower-registry" // sonatype nexus 3.x group registry
    ],
    "register": [
      "url-to-my-internal-bower-registry" // sonatype nexus 3.x internal registry
    ]
  },
  "resolvers": [
    "bower-nexus3-resolver"
  ]
}
```

I am able to search (and register) with my internal registry via cli.

The `bower-nexus3-resolver` is installed globally via npm.

**What I've Tried**

I've added a `.bowerrc` to my local workspace root and installed `bower-nexus3-resolver` as a `devDependency` in npm, but the result is the same.

**Comment by pflannery** [comment]
@willpracht 
I've ensured that bower info API call is from the cwd. 
Will be in v0.21.0
If you still get an issue then reopen

**Comment by willpracht** [comment]
@pflannery Much thanks! Things are working once again! :)
