### ISSUE TITLE
How can I debug and see why isn't the extension working?

### ISSUE THREAD

**Issue by balexandre** [vscode-contrib/vscode-versionlens#103]
I've got a new machine and using an [extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) I've sync my workflow and extensions to VS Code...

I've already disabled, uninstall and install again and again with no effect whatsoever, even check the Output tab under logs (main, shared, window and extension host) and found no logs regarding what might be the issue...

I can't make this extension to work for some odd reason

[![](https://s6.postimg.cc/62nki5i5d/screenshot_9.png)](https://s6.postimg.cc/62nki5i5d/screenshot_9.png)

**Comment by hemantjadon** [comment]
Same is happening with me. It is taking a lot of time to load, and then it again refreshes after sometime  :(

**Comment by pflannery** [comment]
To diagnose issues in vscode you need to go to the developer tools  and read the console output

![image](https://user-images.githubusercontent.com/1727302/40836480-79b5d42e-65c9-11e8-8728-33b8171f7d89.png)

**Comment by LayZeeDK** [comment]
I have been experiencing this issue today. Are you able to run `npm install` or `yarn install` in the project directory? If not, you are probably being rate limited from the NPM regitstry by CloudFlare.

Visit https://registry.npmjs.org/. A JSON file should display. If _Error 1015_ is displayed, CloudFlare has temporarily banned you from NPM. Wait approx. 10 minutes and try again.

Version Lens is what is hammering NPM when you are changing a lot of package dependencies.

**Comment by uberspeck** [comment]
The extension isn't working for me either. I've tried uninstalling/reinstalling and also deleting the extension folder [as suggested (#50)](https://github.com/vscode-contrib/vscode-versionlens/issues/50#issuecomment-298472169). Not getting any errors in the dev tools console either. I'm running VSCode 1.25.0 (just updated).

**Comment by pflannery** [comment]
@LayZeeDK I've never once hit a rate limit on npm. 

It would be nice to cache the npm results like it does with github package queries.

A workaround is to turn off automatic resolution by default using `versionlens.showVersionLensesAtStartup` and manually turn it on each time you need to view  version information in a package.

![image](https://user-images.githubusercontent.com/1727302/44157045-5cb3bb00-a0a9-11e8-9ae4-a0cfe749c96b.png)

**Comment by pflannery** [comment]
@uberspeck what OS are you using?

**Comment by uberspeck** [comment]
@pflannery MacOS 10.13.6 (High Sierra)

**Comment by mrgrauel** [comment]
I have the same error with VSC Version 1.28.2 and Version Lens 0.22.0. Also tried to reinstall multiple times

**Comment by aMarCruz** [comment]
I have the same issue, none of the solutions was useful.
VSCode: 1.28.2
Version Lens: 0.22.0
Linux Mint 18

**Comment by postb99** [comment]
I have a strange error. I deleted the extension folder and reinstalled as suggested above, but I have the same error message in Dev Tools, with another file/directory name, it ends with "12" instead of "10":

`no such file or directory, open 'C:\Program Files\Microsoft VS Code\extension-output-#12'`

Is it related to Windows' security ?

My env:
VS Code 1.28.2 (x64)
Version Lens 0.22.0
Win 7

**Comment by terwort** [comment]
I was getting this same issue. I checked the console from the developer tools and noticed it was throwing an error about not being logged into npm. After running npm login, and signing in successfully, I rebooted vscode and the extension started working. I hope this helps!

**Comment by pflannery** [comment]
@postb99 If @terwort solution doesnt work can you create a seperate issue for your problem. Thanks

**Comment by postb99** [comment]
@terwort yes we both had issues related to login/auth. So it's ok for me after global npm config change (as stated in my edit). Sorry @pflannery if I was off-topic.
