### ISSUE TITLE
Broken local modules.

### ISSUE THREAD

**Issue by Ebuall** [vscode-contrib/vscode-versionlens#104]
When you have dependency like this:
```
    "my-module": "../my-module",
```
extension keeps spinning and you can't it turn of. Once you comment out this dependency it works.
Would be nice to ignore lines like this.

**Comment by pflannery** [comment]
The spinning issue is a bug that will be fixed in 0.21.1

For local file paths you need to specify ```file:``` before the path

So it should be
```
 "my-module": "file:../my-module",
```
