### ISSUE TITLE
Nuget Invalid version entered

### ISSUE THREAD

**Issue by latop2604** [vscode-contrib/vscode-versionlens#105]
VersionLens report `Invalid version entered` but exists in nuget.org (https://www.nuget.org/packages/AngleSharp/0.9.9.2)

![image](https://user-images.githubusercontent.com/2058133/41562364-9f3b8a96-734c-11e8-93b5-30967a8b62b6.png)

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="0.9.9.2" />
    <PackageReference Include="CloudFlareUtilities" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>

</Project>```

Conf:
Vs Code 1.24.1
VersionLens : 0.21.1

**Comment by frankyjuang** [comment]
Same here.
Seems like 4 components in version numbers aren't supported. 
Hi @pflannery, is this extension still actively maintained? I had some small issues with dotnet support, and would love to help making it better!

**Comment by pflannery** [comment]
@latop @frankyjuang No 4 components is not supported. Its follows https://docs.microsoft.com/en-us/nuget/reference/package-versioning#semantic-versioning-200
