### ISSUE TITLE
Prereleases and SemVer range syntax not working

### ISSUE THREAD

**Issue by gaui** [vscode-contrib/vscode-versionlens#106]
Prereleases and SemVer range syntax is not working. I have version 0.21.1 of Version Lens.

For example I have `"gatsby": "^2.0.0-beta.11"` in my package.json file. Version Lens displays:

![](https://i.imgur.com/tj4guO7.png)

Because I have a prerelease and the `^` symbol, it should display the latest prerelease, which is `2.0.0-beta.13`

**Comment by pflannery** [comment]
@gaui To see the latest prerelease you need to enable tagged versions.

![image](https://user-images.githubusercontent.com/1727302/44156782-af5ff6da-a0a8-11e8-948d-8ef790d35296.png)

**Comment by gaui** [comment]
Thank you @pflannery - did not know that. Closing.
