### ISSUE TITLE
Support for Maven artifacts (Java dependencies)

### ISSUE THREAD

**Issue by brunoborges** [vscode-contrib/vscode-versionlens#107]
In the Java world, most projects use build tools like [Maven](https://maven.apache.org) or [Gradle](https://gradle.org/). In either way, dependencies are published Java artifacts available on Maven Central (http://search.maven.org/). 

Example of `pom.xml`:
```xml
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>
```

Example of `build.gradle`:
```groovy
dependencies {
  testCompile 'junit:junit:4.12'
}
```

Maven Central holds an index that can be cached locally and updated from time to time. The index is available at https://maven.apache.org/repository/central-index.html.

Besides Maven Central, other repositories might be configured either on project's specific pom.xml/build.gradle, or globally (settings.xml for Maven). This can be a future enhancement. Supporting Maven Central would be a tremendous benefit already.

**Comment by fcrespo82** [comment]
Hi! I needed that too so I began to develop something... But I need some help in it.. 
I already was able to search and get all versions for a package on maven central, I am having trouble showing the lens with the data.. can you help me with some directions? My fork is [here](https://github.com/fcrespo82/vscode-versionlens/tree/maven-integration)

**Comment by fcrespo82** [comment]
Getting there
![image](https://user-images.githubusercontent.com/462171/44941729-9824d980-ad79-11e8-9f33-74704bcc55d3.png)

I think I got it... Just need to mess around with the tag and versions values...

After that I need to resolve the problem of replacing the version number without the quotes.

Hey @brunoborges can you help me test?

**Comment by pflannery** [comment]
@fcrespo82 The dotnet parser also parses xml for dependencies. The [collectFromChildVersionTag](https://github.com/vscode-contrib/vscode-versionlens/blob/69f70f6c1bc53b86e266496a6435814080ce04ec/src/providers/dotnet/dotnetDependencyParser.js#L79-L97) function looks for child version elements and extracts the version from them.

**Comment by fcrespo82** [comment]
Yep, I used that. The problem I'm having now is that maven versions don't follow semver.
The field is of string type. this makes it harder to parse.

**Comment by brunoborges** [comment]
hey @fcrespo82, how can I test your tweaks ?

**Comment by brunoborges** [comment]
I should remove VersionLens extension first, right?

**Comment by fcrespo82** [comment]
No, you don't need to. In this new window the development version will override the current...

**Comment by fcrespo82** [comment]
@brunoborges I forgot to say that you should checkout the branch maven-integration

**Comment by fcrespo82** [comment]
Hi @pflannery I'm working on some improvements on maven support but I'd like to discuss some approaches before I make a new pull request.

Do you think it is better do give the user the option to inform another location of users `settings.xml` ([link to documentation](https://maven.apache.org/settings.html)) path
The relevant part is:
> There are two locations where a settings.xml file may live:
> 
> The Maven install: ${maven.home}/conf/settings.xml
> A user’s install: ${user.home}/.m2/settings.xml

Or the option to set the maven binary location and use the command option `mvn help:effective-settings` ([link to documentation](https://maven.apache.org/plugins/maven-help-plugin/effective-settings-mojo.html))
Which states that:
> Displays the calculated settings as XML for this project, given any profile enhancement and the inheritance of the global settings into the user-level settings.

to get the desired location and maybe give the user the option to pass the flag `-s` that will inform the `settings.xml` to use?

I don't know if I made the options clear, but I can answer any question that may be left out of those approaches.

Thanks again for the awesome extension..

**Comment by pflannery** [comment]
@fcrespo82 sounds like its easier to use the mvn binary. Would be nice to avoid having to specify the mvn path if possible.

**Comment by fcrespo82** [comment]
I can use the one that is on the PATH, but if it's not found I can fallback to how I am doing now or use [Maven Wrapper](https://github.com/takari/maven-wrapper). What do you think?

**Comment by fcrespo82** [comment]
I made a new PR #114 solving some drawbacks I found in the first version of the implementation.

**Comment by tomByrer** [comment]
Could this be closed?  Seems quite a bit of Maven support has been added?

**Comment by brunoborges** [comment]
Indeed, this is already supported by the Maven extension from Microsoft.
