### ISSUE TITLE
Unlisted versions are also considered

### ISSUE THREAD

**Issue by frankyjuang** [vscode-contrib/vscode-versionlens#108]
Currently, `PackageBaseAddress` resource is used to get all available versions of nuget package. However, by using that endpoint, versions including listed and unlisted are all returned. 

> This list contains both listed and unlisted package versions.
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#enumerate-package-versions

For example, versionslens indicates the latest version of package `Microsoft.Rest.ClientRuntime` (https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/) is `3.0.3`, but the actual latest version is `2.3.11` (all 3.x.y are unlisted).

**Comment by frankyjuang** [comment]
Seems like `SearchAutocompleteService` resource filters out the unlisted versions by design. 
https://docs.microsoft.com/en-us/nuget/api/search-autocomplete-service-resource#enumerate-package-versions
```bash
curl "https://api-v2v3search-0.nuget.org/autocomplete?id=microsoft.rest.clientruntime&prerelease=true&semVerLevel=2.0.0"
```

@pflannery I can work on the change if you also agree we should get rid of the unlisted versions.

**Comment by pflannery** [comment]
@frankyjuang Looks like `Microsoft.Rest.ClientRuntime` hasn't used semver pre-release identifiers and therefore present themselves as released versions. That's why it 3.0.3 appears as the latest version. 

For example see bootstrap https://api-v2v3search-0.nuget.org/autocomplete?id=bootstrap&prerelease=true. All their pre-releases have identifiers which is consistent with the semver spec.

**Comment by pflannery** [comment]
The other thing is: if we removed unlisted entries then the tagged versions would stop working.

![image](https://user-images.githubusercontent.com/1727302/45430251-e9e43280-b69c-11e8-84f4-b11559dccade.png)

**Comment by pflannery** [comment]
@frankyjuang Thinking further, I would be happy for a pull request to update the url which is configurable via setting. That way someone could set prerelease=false if they wish to disable it all together

**Comment by frankyjuang** [comment]
Pre-release version and unlisted version are different. As for package *bootstrap*, version `3.3.6.1` is unlisted (https://www.nuget.org/packages/bootstrap/3.3.6.1). According to nuget, 
> This could mean that the package is deprecated or shouldn't be used anymore. 
![image](https://user-images.githubusercontent.com/6175880/45435739-ba0c4d80-b6e3-11e8-9caf-056ded99e989.png)

**Comment by frankyjuang** [comment]
Available versions collected from `https://api.nuget.org/v3-flatcontainer/` contain *unlisted* ones while versions from `https://api-v2v3search-0.nuget.org/autocomplete?id=bootstrap&prerelease=true` don't. That's why I proposed to use the latter one instead.

`https://api.nuget.org/v3-flatcontainer/bootstrap/index.json`
![image](https://user-images.githubusercontent.com/6175880/45436047-6fd79c00-b6e4-11e8-98b6-d23bbb220292.png)

`https://api-v2v3search-0.nuget.org/autocomplete?id=bootstrap&prerelease=true`
![image](https://user-images.githubusercontent.com/6175880/45436088-8847b680-b6e4-11e8-9c9c-6eaf935fa0f8.png)

**Comment by pflannery** [comment]
@frankyjuang I see now. As long as it still contains the pre-releases by default then I'm fine with removing the unlisted versions
