### ISSUE TITLE
support lerna / monorepo

### ISSUE THREAD

**Issue by ColonelBundy** [vscode-contrib/vscode-versionlens#110]
Currently show's packages as not installed

**Comment by pflannery** [comment]
@ColonelBundy Can you provide more details and an example?

**Comment by ColonelBundy** [comment]
> @ColonelBundy Can you provide more details and an example?

[lernajs](https://github.com/lerna/lerna) is a tool for managing monorepos. Due to the way it works, node_modules reside outside of the base path of the project you are working on. Some modules however will reside in the node_modules folder of the project and those are the only ones versionlens picks up.

Best way for me to demonstrate this would be for you to install lerna and initalize a new project and navigate to the ```packages``` folder. Then create a new package and look inside ```package.json``` of your package and you'll see what I described above.

**Comment by ColonelBundy** [comment]
> @ColonelBundy Does lernajs have an API? and how would we be able to identify lernajs dependencies from normal NPM dependencies?

Best way would be to look for ```lerna.json``` and then look for node_modules in the same folder.

**Comment by jas99** [comment]
+1 I was about to write same issue
@pflannery 
You can take a quick look at lerna list command.

**lerna list --json**
```
info cli using local version of lerna
lerna notice cli v3.4.0
[
  {
    "name": "prisma-gen",
    "version": "1.0.0",
    "private": false,
    "location": "D:\\repo\\keybase\\skooly\\skooly\\packages\\lib\\prisma-gen"
  },
  {
    "name": "@skooly/server",
    "version": "1.0.0",
    "private": false,
    "location": "D:\\repo\\keybase\\skooly\\skooly\\packages\\server"
  }
]
```
 https://github.com/lerna/lerna/blob/master/commands/list/index.js

Basically what lerna is doing is not too complicated anyways. I can help you implementing it.
We basically have to scan for package.json files inside of our project except for those in node_module folders or not included in lerna.json. We will get lerna package name and version and you can pass that to extension. 

By default lerna.json look like this. 
```
{
  "packages": [
    "packages/**"
  ],
  "version": "0.0.0"
}
```

Lemme me now if you wanna start on this; will help you out.

Thx

**Comment by jas99** [comment]
Hey @ColonelBundy 
If you can quickly walk me through you extension; maybe over video or audio chat; I can create and send you PR.

Thx

**Comment by AlexLeung** [comment]
I think ideally, lerna support for vscode-versionlens would be reading the lerna.json file, then
1. For dependencies that are a part of the monorepo, the lens shows the info of the package in a different color than packages found on npm
2. Changing the version in one package.json changes the version in all packages of the monorepo.

While we are talking about monorepos, we could also look at yarn workspaces as well.

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/110
