### ISSUE TITLE
Won't pick up latest npm version

### ISSUE THREAD

**Issue by lbergman** [vscode-contrib/vscode-versionlens#113]
I'm using version lens 0.21.2, and have trouble with latest version being picked up.

For example in package json I have "^1.0.5-rc.1" as version (private module, so unfortunately cannot give you module as example).
Doing npm view version on the package results in '1.0.5' and dist-tags gives { latest: '1.0.5' }, which both are correct since we remove the rc tag when doing a release. But it seems like unless it is a numerically lower version, latest will not be picked up. So if I change version to 1.0.4, latest is picked up as 1.0.5, but 1.0.5 with any suffix will count as newer than 1.0.5 regardless of what is newest and tagged as latest.

**Comment by pflannery** [comment]
@ibergman Sound strange as this extension uses `npm view` to retrieve the results. Can you provide a screenshot?

**Comment by lbergman** [comment]
![package](https://user-images.githubusercontent.com/741170/46414845-4b3f7480-c724-11e8-965b-43a2bd259993.PNG)
![cmd](https://user-images.githubusercontent.com/741170/46414854-50042880-c724-11e8-9bc3-9959ad24d835.PNG)

**Comment by lbergman** [comment]
And if I change version in package to something lower than 1.0.5:
![package2](https://user-images.githubusercontent.com/741170/46414934-85107b00-c724-11e8-9a6c-d328007af744.PNG)

**Comment by pflannery** [comment]
Having a bit of difficulty recreating. 
I tried the following with bootstrap

```sh
$ npm view bootstrap@^4.0.0-beta.3 version
bootstrap@4.0.0-beta.3 '4.0.0-beta.3'
bootstrap@4.0.0 '4.0.0'
bootstrap@4.1.0 '4.1.0'
bootstrap@4.1.1 '4.1.1'
bootstrap@4.1.2 '4.1.2'
bootstrap@4.1.3 '4.1.3'
```

I see the expected with versionlens

![image](https://user-images.githubusercontent.com/1727302/46419026-dc165000-c724-11e8-9cc7-b5f8be7ea396.png)

@lbergman Can you run `npm view @hacksawstudios/analytics@^1.0.5-rc.1 version` and post here?

**Comment by pflannery** [comment]
This test seemed more similar to your package but I still can't recreate 

```sh
$ npm view @angular/animations@^6.1.0-rc.3 version
@angular/animations@6.1.0-rc.3 '6.1.0-rc.3'
@angular/animations@6.1.0 '6.1.0'
@angular/animations@6.1.1 '6.1.1'
@angular/animations@6.1.2 '6.1.2'
@angular/animations@6.1.3 '6.1.3'
@angular/animations@6.1.4 '6.1.4'
@angular/animations@6.1.6 '6.1.6'
@angular/animations@6.1.7 '6.1.7'
@angular/animations@6.1.8 '6.1.8'
@angular/animations@6.1.9 '6.1.9'
```


Also works as expected

![image](https://user-images.githubusercontent.com/1727302/46419679-54314580-c726-11e8-8e47-f34d1e641782.png)

**Comment by lbergman** [comment]
```npm view @hacksawstudios/analytics@^1.0.5-rc.1 version``` returns ```1.0.5-rc.1```

The difference with the examples you tried is that with the modules for which it fails, latest has same number as current, just without any suffix. If latest has a higher number it always works. 
I can set up a package with the same conditions later today so you have a good example to test.

**Comment by pflannery** [comment]
@lbergman It's ok I've managed to reproduce. 

```
$ npm view @angular-redux/store@^9.0.0-beta.0 version
@angular-redux/store@9.0.0-beta.0 '9.0.0-beta.0'
@angular-redux/store@9.0.0 '9.0.0'
```

But I see Latest in the package json
![image](https://user-images.githubusercontent.com/1727302/46457401-1e35a500-c7aa-11e8-94ca-35d7eb4d58c3.png)

Will investigate
