### ISSUE TITLE
Add support for crates.io

### ISSUE THREAD

**Issue by sergeysova** [vscode-contrib/vscode-versionlens#116]
[Rust](https://www.rust-lang.org/) has a package manager [Cargo](https://doc.rust-lang.org/cargo/) and package registry [crates.io](https://crates.io/).

Cargo uses [toml](https://github.com/toml-lang/toml) as config language.
Manifest format [here](https://doc.rust-lang.org/cargo/reference/manifest.html)
Documentation published at [docs.rs](https://docs.rs/)

Crates API [docs](https://github.com/rust-lang/crates.io/blob/master/docs/BACKEND.md#routes) and [sources](https://github.com/rust-lang/crates.io/blob/master/src/router.rs).

Also rust has `extern crate name;` directive to import crate in code ([docs](https://doc.rust-lang.org/book/ch07-02-modules-and-use-to-control-scope-and-privacy.html#using-external-packages))

**Comment by Bond-009** [comment]
@sergeysova ‘extern crate name;’ isn’t needed anymore in Rust 2018

**Comment by sergeysova** [comment]
@Bond-009 	I know. But not all projects updated yet.

**Comment by pflannery** [comment]
ok things I understand so far to implement this



Cargo.toml is the package file

toml dependency entries are found at

```toml

[dependencies]
foo = "1.0" # or
bar = { version = "1.0" }

[dev-dependencies]

[build-dependencies] 

[features] # looks likes macros and raw values here ?

```

Api url for getting a package version list is : `https://crates.io//api/v1/crates/${PackageName}/versions`

Extracting the latest versions for a package would come from the Json result

```js
{
    "versions": [
        {  // omitted other properties
            "num": "x.x.x"
        },
        {
            "num": "x.x.x"
        },
        // etc....
    ]
}
```

**Comment by Teoxoy** [comment]
Extension that does this already: https://github.com/serayuzgur/crates - might help with the development of this feature

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/116
