### ISSUE TITLE
Invalid NuGet package semver versions breaks extension

### ISSUE THREAD

**Issue by Hoffs** [vscode-contrib/vscode-versionlens#119]
Similar to #105 but this completely breaks the extension. If referenced package doesn't follow semantic versioning (e.g. https://www.nuget.org/packages/System.Data.SQLite ) it throws exception at `buildTagsFromVersionMap` and bubbles up breaking the extension. No other packages show version info either at that point.

```
[error] Cannot read property 'version' of undefined: TypeError: Cannot read property 'version' of undefined
	at Object.buildTagsFromVersionMap (...\.vscode\extensions\pflannery.vscode-versionlens-0.22.0\out\extension-bundle.js:1046:77)
	at ...\.vscode\extensions\pflannery.vscode-versionlens-0.22.0\out\extension-bundle.js:2970:48
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by pflannery** [comment]
@Hoffs this issue is now fixed in 0.27.0.
