### ISSUE TITLE
Show both latest pre-release and stable versions

### ISSUE THREAD

**Issue by eamodio** [vscode-contrib/vscode-versionlens#12]
Not sure if this really applies to anything but Nuget, but it would be great to show both the latest pre-release package and stable package (although if the latest stable is later than the pre-release there isn't a reason to show that).

Thanks!

BTW Awesome extension!

**Comment by pflannery** [comment]
I want this to happen. I don't have a need at the moment but accepting PRs. @eamodio

**Comment by jp7677** [comment]
This would be very useful, also for git releases. Especially since even Microsoft is pushing a lot of previews to NuGet.

**Comment by pflannery** [comment]
Related with https://github.com/vscode-contrib/vscode-versionlens/issues/37#issuecomment-271171065

**Comment by pflannery** [comment]
This feature is now implemented for npm and jspm in 0.14.0 but not yet for dotnet

**Comment by pflannery** [comment]
This is implemented in [0.17.0](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0170)
