### ISSUE TITLE
Extension cannot work when *.json file association is configured

### ISSUE THREAD

**Issue by mudoo** [vscode-contrib/vscode-versionlens#122]
I configured *.json file association as "JSON with Comments"(jsonc). Then extension can't work...

Maybe #103 is the same problem...

**Comment by lonix1** [comment]
It still doesn't work. Should not be closed.

**Comment by pflannery** [comment]
How do you get npm to work with jsonc ?

**Comment by mudoo** [comment]
@pflannery Just configured *.json file association as jsonc. The "package.json" is still a standard json file.

Delete this line, it worked.
https://github.com/vscode-contrib/vscode-versionlens/blob/17b5ebc7e3a38218b4187701964a1b5ed3b67769/src/providers/npm/npmCodeLensProvider.js#L33

**Comment by MaKCbIMKo** [comment]
@mudoo I've managed to get it work by adding additional files assosiation:
```
"files.associations": {
    "*.json": "jsonc",
    "package.json": "json"
}
```

**Comment by pflannery** [comment]
> @mudoo I've managed to get it work by adding additional files assosiation:
> 
> ```
> "files.associations": {
>     "*.json": "jsonc",
>     "package.json": "json"
> }
> ```

Thanks for posting a solution. Will close
