### ISSUE TITLE
Support for Git

### ISSUE THREAD

**Issue by TheAifam5** [vscode-contrib/vscode-versionlens#13]
Hey, 
Its possible to add support for Git packages?
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by pflannery** [comment]
I want this to happen. I don't have a need at the moment but accepting PRs. @TheAifam5

**Comment by jdforsythe** [comment]
+1. Would be cool if it checked releases on github repos

**Comment by jp7677** [comment]
+1 Would be very cool. I guess the implementation would be quite similar to the current nuget one. The git tags can be obtained using https://api.github.com/repos/:user/:repos/tags or even better https://api.github.com/repos/:user/:repos/releases where one can see the difference between release and pre-release.

E.g.
https://api.github.com/repos/twbs/bootstrap/releases
https://api.github.com/repos/twbs/bootstrap/tags

**Comment by xnnkmd** [comment]
See also, #24 which is closed with a change that was supposed to support this but apparently it does not.

**Comment by pflannery** [comment]
@xnnkmd #24 was not a change to support this. It was a change to include [local-path support](https://docs.npmjs.com/files/package.json#local-paths)

**Comment by xnnkmd** [comment]
Ok. Note also, that npm5 changes the local path option and introduces a ["link" option](https://github.com/npm/npm/pull/1590).

**Comment by pflannery** [comment]
@xnnkmd I think you meant to put https://github.com/npm/npm/pull/15900 as your link goes to something unrelated.

**Comment by pflannery** [comment]
Closing this as it does already support github urls. (Not private git repos)
