### ISSUE TITLE
Support Flutter/Dart

### ISSUE THREAD

**Issue by senpl** [vscode-contrib/vscode-versionlens#130]
Basic support for packages version of flutter .packages files would be great. Without basic version check users only got information about outdated packages, but could resolve them only by manual checking every entry.

**Comment by MegaMattMiller** [comment]
Just came across this extension today. Would love to have Pub support.

**Comment by tm-design** [comment]
This would be fantastic to have. Would be awesome if you could set up a server location to check against as well!

**Comment by pflannery** [comment]
Pub is now supported so closing this.
