### ISSUE TITLE
Migration: please emit ES6 output

### ISSUE THREAD

**Issue by jrieken** [vscode-contrib/vscode-versionlens#132]
We have identified this extension as emitting ES5-JavaScript code *and* extending API-types, like `vscode.Disposable` or `vscode.CompletionItem`. VS Code itself has changed to emit ES6 JavaScript code and too enable `functions` extending from `classes` we have added a utility in our code. Given the small number of es5-emitting extensions that also extend API-types we ask for your help, which is emitting ES6 instead of ES5. 

Thanks and #HappyCoding!

**Comment by jrieken** [comment]
@pflannery fyi this is still an issue

**Comment by pflannery** [comment]
@jrieken This done now. closing thanks
