### ISSUE TITLE
Feature Request: license information

### ISSUE THREAD

**Issue by cilerler** [vscode-contrib/vscode-versionlens#135]
It would be really nice to see license information of the packages like [npm-license-checker](https://www.npmjs.com/package/license-checker) provides.

**Comment by cilerler** [comment]
go away stalebot, I need this issue to stay open

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/135
