### ISSUE TITLE
Add support for showing package diffs (npm)

### ISSUE THREAD

**Issue by eamodio** [vscode-contrib/vscode-versionlens#137]
I think it would be awesome if there was a quick/easy way to show a diff of a package compared to an upgraded version.

Here is a tool that can be leveraged to provide the actual diff:
https://diff.intrinsic.com/

Here is the announcement about it: https://medium.com/intrinsic/introducing-package-diff-for-npm-e6487cc9b434

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/137
