### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sgvallala** [vscode-contrib/vscode-versionlens#139]
- Issue Type: `Performance`
- Extension Name: `vscode-versionlens`
- Extension Version: `0.22.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.1`

[pflannery.vscode-versionlens-unresponsive.cpuprofile.txt](https://github.com/vscode-contrib/vscode-versionlens/files/2963074/pflannery.vscode-versionlens-unresponsive.cpuprofile.txt)

**Comment by denkristoffer** [comment]
There's multiple open issues about this: #134 and #136 can be closed for this one, since it has the `cpuprofile.txt` file attached.
