### ISSUE TITLE
Old version shown for package.json

### ISSUE THREAD

**Issue by clavecoder** [vscode-contrib/vscode-versionlens#14]
I have `glob-fs` referenced in package.json. Latest version is 0.1.7 (from `npm view glob-fs`)

![image](https://cloud.githubusercontent.com/assets/3524633/17271350/cc9a6bc4-563e-11e6-9636-13fdff198f81.png)

but versionlens shows 0.1.6:

![image](https://cloud.githubusercontent.com/assets/3524633/17271354/eeb82de0-563e-11e6-9e20-0cf781aea330.png)

**Comment by clavecoder** [comment]
Well that was fast...

Looks like the issue is with NPM itself. Weird:

![image](https://cloud.githubusercontent.com/assets/3524633/17271416/4928f4b6-5640-11e6-8a0d-9946ba7c0de8.png)

Any ideas?

**Comment by pflannery** [comment]
@clavecoder 

When I run `npm view glob-fs` I see v0.1.6
But the author in your first screen shot shows a different author. 



![image](https://cloud.githubusercontent.com/assets/1727302/17278386/0f47d9f6-578f-11e6-88ca-e53c9f6fa17d.png)

`glob-fs` is at https://www.npmjs.com/package/glob-fs and the latest is at 0.1.6

**Comment by clavecoder** [comment]
Weird.
