### ISSUE TITLE
Feature Request:  Show Latest Minor/Patch Version for Pinned Dependencies

### ISSUE THREAD

**Issue by SteffenKn** [vscode-contrib/vscode-versionlens#140]
It would be nice to see the latest non-major version for pinned dependencies.

For example, if you have `example-package"` pinned to `1.0.0` in your package.json and there are two newer versions `1.1.0` and `2.0.0`.
It would be nice to see that `1.1.0` is the latest `1.x.x` version and `2.0.0` is the latest version.

**Comment by Blackbaud-ChristiSchneider** [comment]
@pflannery Can this be reopened? We have some dependencies that can't be updated to the latest major version yet but want to know when they are out of date for minor and patch versions.
