### ISSUE TITLE
Support <PackageReference Update="Name"> directives

### ISSUE THREAD

**Issue by Alxandr** [vscode-contrib/vscode-versionlens#143]
I'm trying out https://github.com/Microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions which has me writing dependencies like `<PackageReference Update="NodaTime" Version="2.4.5" />` using `Update` instead of `Include`. This results in `undefined could not be found`. Could the dotnet provider be updated to do something like `node.Include || node.Update` for the name?

**Comment by pflannery** [comment]
@Alxandr yes I dont see why not. I think the logic is around [this area](https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/providers/dotnet/dotnetDependencyParser.js#L37)

**Comment by pflannery** [comment]
This was fixed in v0.24.0.
