### ISSUE TITLE
Always downgrades packages, does not use semantic versioning or the ^ symbol

### ISSUE THREAD

**Issue by Yzrsah** [vscode-contrib/vscode-versionlens#144]
Here the version should be greater `^` than `10.0.0-alpha.16`.

![Downgrades](https://i.imgur.com/Gvccsx5.png)

VersionLens will always downgrade the package and does not utilize semantic versioning.

`^` from https://semver.npmjs.com/:
> include everything greater than a particular version in the same major range

**Comment by pflannery** [comment]
@Yzrsah 

> VersionLens will always downgrade the package and does not utilize semantic versioning.

It purposely offers a downgrade option to **latest release** when the version entered is a prerelease. 
In your case 10.0.0-alpha.16 is the latest prerelease.
