### ISSUE TITLE
Support v2 NuGet repositories

### ISSUE THREAD

**Issue by psaxton** [vscode-contrib/vscode-versionlens#149]
At least one [common nuget package server](https://en.wikipedia.org/wiki/ProGet) does not support v3 feeds and [doesn't have v3 support on their roadmap](https://inedo.com/support/questions/7377#inline-post-9007). A configuration value should enable querying v2 package feeds in order to support these private feeds.

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/149
