### ISSUE TITLE
Support for private packages

### ISSUE THREAD

**Issue by peterjuras** [vscode-contrib/vscode-versionlens#15]
Hi!

Do you think it would be possible to add support for private packages? E.g. packages that are only visible to an organization? Right now they are just 404ing.

I think (not sure) this might be possible if the extension would use the real npm package to get the package information, since it might use the local auth key by default.

Otherwise thanks for the great extension!

**Comment by pflannery** [comment]
Thanks @peterjuras 

The npm api url is currently hard coded here -> https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/providers/npmCodeLensProvider.js#L68

If you have an api to query the private registry then this feature could be possible. https://docs.npmjs.com/misc/registry#can-i-run-my-own-private-registry

**Comment by peterjuras** [comment]
Ah what I actually meant are privately scoped packages ^^ meaning private modules that live within npmjs.com

**Comment by reflectiondm** [comment]
Hi!
Looks like this issue is fixed, but I have a simmilar usecase with internal npm registries. We have an internal registry set up and the reference is in `.npmrc` file. Currently internal packages just show 404 because npm link is hardcoded.
Could it be made possible to also check npm registries from `.npmrc` file?
I could also create a PR with the fix if you are interested.

**Comment by pflannery** [comment]
I'm not sure how we can access private modules via the web API.

It might be better to use the npm command instead of the web api i.e. `npm view <package>@latest version`
This would have to work on Linux, Mac and Windows.

**Comment by peterjuras** [comment]
I just did a quick test on macOS and it seems to work using the npm command:

```js
const npm = require('npm');

npm.load({}, (err, npm) => {
  npm.view('@private/package', (err, res) => {
    console.log(res);
  });
});
```

npm version: 3.10.8

I would assume this works for every OS? It picked up the auth token without any required configuration.

**Comment by pflannery** [comment]
@reflectiondm 0.8.0 should be available now. Could you check if internal registries set up using the reference in .npmrc files works? thanks

**Comment by reflectiondm** [comment]
@pflannery Tested on Windows. Works as charm! Thanks =)

**Comment by pflannery** [comment]
@reflectiondm great! thanks
