### ISSUE TITLE
Unnecesery 0 character is appended to the version string every time button is pressed

### ISSUE THREAD

**Issue by mptorz** [vscode-contrib/vscode-versionlens#154]
Every time I press the button `latest` the extension appends a `0` character to the version string as shown on [the attached gif](https://gyazo.com/08dd853499cb9250e17f7cb2eedbe7a6)

Extra info:
Version Lens: 0.24.0
Vscode: 1.36.0

EDIT: sorry actually the title is misleading. It doesn't only happen with `0` character, but with every number like:
[another example](https://gyazo.com/5ee3991c7cb02737df580d047e22b670)

**Comment by mptorz** [comment]
bump

**Comment by WORMSS** [comment]
That is strange, when I click that button, it changes to "latest" and there is no longer any link to click on.

**Comment by pflannery** [comment]
Strange. I cant recreate. Which OS was this on?

**Comment by pflannery** [comment]
This has been fixed in 0.27.0. Will close
