### ISSUE TITLE
Stuck on Analyzing dependencies

### ISSUE THREAD

**Issue by cpxPratik** [vscode-contrib/vscode-versionlens#157]
Does not work on any project, simply gets stuck on `Analyzing dependencies`

For e.g.
Dependencies on `Package.json`

```
{
  "peerDependencies": {
    "pouchdb-browser": "^7.0.0",
    "vue": "^2.5.16",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "webpack": "^3.11.0",
    "webpack-merge": "^4.1.2"
  }
}
```

vscode version: 1.37.1
extension version: 0.24.0
node version: v10.16.0
os version: Linux generic-pc 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kambbado** [comment]
If you use a local registry check your tokens in your C:\Users\<UserUserName>\,npmrc file, they may have expired.

**Comment by cpxPratik** [comment]
The cause was gemfuy proxy configuration with `npm-proxy.fury.io` on ~/.npmrc. As soon as I removed the line, extension is working. So the extension does not work with gemfury npm proxy.
