### ISSUE TITLE
Feature Request: Hide "Latest" 

### ISSUE THREAD

**Issue by renarsvilnis** [vscode-contrib/vscode-versionlens#160]
Hi,
I really find version lens useful to quickly update dependencies instead of manually updating `package.json`, but I find it annoying that it "doubles" length (vertical space) of the dependencies it makes it actually harder at a glance to see that needs to be updated as 80% of the lines are just "Latest".

So I propose adding the ability to hide the "Latest" messages, maybe also "Loading" state and have only visible when there is actually something to update.

**Comment by PachowStudios** [comment]
A potential issue with this is that as the version info loads, the spacing of the file will jump around.

**Comment by renarsvilnis** [comment]
@PachowStudios  Yeah, similar as `GitLens` does for per line `git-blame`

![image](https://user-images.githubusercontent.com/3515099/65952009-7a74e880-e441-11e9-8be4-2ffdd60dc460.png)

**Comment by SlothFriend** [comment]
Regardless of where the info is displayed, having the option to hide latest would be great. As soon as I enabled the extension (just now), I felt two things:
1. This is great!
2. I wish I could disable all those "latest" labels
