### ISSUE TITLE
Stuck on "Analyzing dependencies"

### ISSUE THREAD

**Issue by bjoernbg** [vscode-contrib/vscode-versionlens#161]
Hey,
thanks for this great little plugin. Recently it stopped working for me, though. It always hangs on "Analyzing dependencies". I tried deleting all VS Code preferences, all installed extensions and also deleted ~/.npmrc but nothing helped.

The Developer Tools show this error message:
`Error: NPM: parseNpmArguments Error: certificate has expired` in `.vscode/extensions/pflannery.vscode-versionlens-0.24.0/out/extension-bundle.js:1358:19`

I even looked at that code but couldn't figure out what was going wrong. What can I do to pinpoint this problem?

**Comment by pflannery** [comment]
@bjoernbg  I'm not sur emyself. Is this still happening in 0.26.2 ?

**Comment by pflannery** [comment]
This issue was resolved in a 0.27.0 so will close.
