### ISSUE TITLE
Enhance Progress Indicator

### ISSUE THREAD

**Issue by terwort** [vscode-contrib/vscode-versionlens#163]
In the past, and even now, people sometimes get stuck with "Analyzing Dependencies". I was wondering if it would be possible to add some sort of status indicator to show the user what exactly is going on? I'd love to see where in the process it is taking so long instead of always seeing the analyzing message. Possibly a number system with the current package being analyzed? Something like "3/25 redux". Thanks!

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/163
