### ISSUE TITLE
Add a way to track versions from multiple registries

### ISSUE THREAD

**Issue by hwatersiv** [vscode-contrib/vscode-versionlens#164]
Ill start by say I really love this tool. My company uses a private registry along with npm. Version lens appears to use the `.npmrc` but, the `.npmrc` can only hold 1 registry reference at a time. Would it possible to show version for not only my private registry but also the npm registry as well?

**Comment by pflannery** [comment]
It uses `npm view` to analyse dependencies so it cannot be done in this plugin.

The only option I see at the moment is to setup your private  registry to fallback to the npm registry when a package doesnt exist

See

https://stackoverflow.com/questions/47871996/how-to-define-fallback-registry-in-global-npmrc-file

and

https://stackoverflow.com/questions/48417082/how-to-config-several-private-repository-and-public-repository-in-npm/48417335#48417335
