### ISSUE TITLE
Show "next" version

### ISSUE THREAD

**Issue by magnattic** [vscode-contrib/vscode-versionlens#166]
I fix all my package versions. 
Oftentimes I want to update to the latest beta/next version instead of the latest stable version. It would be great to have this as an option besides the "latest" version in VersionLens.

How it looks like now:
> Fixed to 8.2.2 | latest: 8.2.3
![no latest](https://i.imgur.com/1GzNQT5.png)

What I would like to see:
> Fixed to 8.2.2 | latest: 8.2.3 | next: 9.0.0-next.0

This would give me the option to select between updating to stable or next versions.

**Comment by magnattic** [comment]
Any chance this could get implemented? Is the extension even still being maintained?

**Comment by pflannery** [comment]
@magnattic  you can already show tagged versions. You can also set which tagged versions you prefer to see by setting `versionlens.npm.distTagFilter` and permenatly show tagged version using `versionlens.showTaggedVersionsAtStartup`

Their is a show\hide tag button in the toolbar also.

![image](https://user-images.githubusercontent.com/1727302/81138937-b930cb00-8f5b-11ea-922a-f26602164d48.png)
