### ISSUE TITLE
Add support for 4-segment versions

### ISSUE THREAD

**Issue by Eilon** [vscode-contrib/vscode-versionlens#169]
This was discussed previously in these issues (and closed):

1. https://github.com/vscode-contrib/vscode-versionlens/issues/146
1. https://github.com/vscode-contrib/vscode-versionlens/issues/119
1. https://github.com/vscode-contrib/vscode-versionlens/issues/105

Given that NuGet clearly _does_ support 4-segment versions, and given that there are some very popular packages that use 4-segment versions, I think it would be best for users of this extensions to not see these flagged as invalid. NuGet doesn't require SemVer 2.0, though it does support it.

![image](https://user-images.githubusercontent.com/202643/69078364-94b45700-09ec-11ea-8941-2764bf1c7cf6.png)

I do think that packages _should_ use 3-segment versions, but there's no requirement that they do so.

Could the current "error message" reported by this extensions be softened to something that better reflects what is allowed by NuGet?

**Comment by garie** [comment]
This is pretty important. Many common packages are using 4-segment version numbers now. For example, AWS:
`<PackageReference Include="AWSSDK.Core" Version="3.3.104.21" />`

**Comment by pflannery** [comment]
@Eilon @garie 
This is fixed in 0.27.0. 
4 segment versions are no longer analysed and do not appear with invalid tags.

**Comment by Eilon** [comment]
Thank you so much! Love the add-in!
