### ISSUE TITLE
Add support of multiple NuGet sources

### ISSUE THREAD

**Issue by andrei-m-code** [vscode-contrib/vscode-versionlens#171]
Hello,

This is a great tool. Here is my issue: I have multiple NuGet servers to work with and the tool seems like only supports nuget.org(?), is there a way to enable multiple sources?

Note: This issue could be related to https://github.com/vscode-contrib/vscode-versionlens/issues/149 (Support v2 NuGet feed)

**Comment by Hoffs** [comment]
You can configure to use more than 1 nuget service but they have to support `SearchAutocompleteService` which is not required service.

**Comment by pflannery** [comment]
You can add new sources by either

  - running `dotnet nuget add {source}`. [See more here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source)
 - or by adding service index urls to `versionlens.dotnet.nuget.sources`. 

Only v3 of the nuget api is supported at present
