### ISSUE TITLE
Similar plugins in WebStorm ?

### ISSUE THREAD

**Issue by itning** [vscode-contrib/vscode-versionlens#175]
- Is there a plugin of the same type in webstorm ？
- Is developers have plans to develop plug-ins for webstorm ?

**thanks**

**Comment by pflannery** [comment]
@itning

> Is there a plugin of the same type in webstorm ？

 I haven't used webstorm for years so im not sure if there is an extension like this. I know they used to have a built in nodejs dependency manager ui

> Is developers have plans to develop plug-ins for webstorm ?

No.
