### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by SeasonCCC** [vscode-contrib/vscode-versionlens#181]
I find a small bug in this extensions. Package.json file need to select json language mode(JSON) instand of json with comment(JSONC).

**Comment by pflannery** [comment]
This is a duplicate of #122 

npm doesnt support JSONC so this extension will also not parse JSONC (unless npm changes)

Please try the solution from this comment 

https://github.com/vscode-contrib/vscode-versionlens/issues/122#issuecomment-493410952

**Comment by SeasonCCC** [comment]
thx
