### ISSUE TITLE
Plugin not working with package.json

### ISSUE THREAD

**Issue by wpalombini** [vscode-contrib/vscode-versionlens#183]
Hi all, version lens wont show up on my environment on my package.json.
My setup:
Version: 1.44.0 (system setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

{
  "name": "rescued",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-deploy": "npm version patch && ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "9.1.0",
    "@angular/cdk": "9.2.0",
    "@angular/common": "9.1.0",
    "@angular/compiler": "9.1.0",
    "@angular/core": "9.1.0",
    "@angular/forms": "9.1.0",
    "@angular/material": "9.2.0",
    "@angular/platform-browser": "9.1.0",
    "@angular/platform-browser-dynamic": "9.1.0",
    "@angular/router": "9.1.0",
    "rxjs": "6.5.5",
    "tslib": "1.11.1",
    "zone.js": "0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.901.0",
    "@angular/cli": "9.1.0",
    "@angular/compiler-cli": "9.1.0",
    "@angular/language-service": "9.1.0",
    "@types/node": "13.11.0",
    "@types/jasmine": "3.5.10",
    "@types/jasminewd2": "2.0.8",
    "codelyzer": "5.2.2",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "3.1.1",
    "karma-jasmine-html-reporter": "1.5.3",
    "protractor": "6.0.0",
    "ts-node": "8.8.2",
    "tslint": "6.1.1",
    "typescript": "3.8.3"
  }
}

![image](https://user-images.githubusercontent.com/7042156/78955080-855fb280-7b21-11ea-8df7-36c4cb6ced3b.png)

**Comment by wpalombini** [comment]
Hi all, I have finally found the issue: The language mode was set to JSON Formatter. All that I had to do was to set it to JSON only. It would be nice to have some sort of notification around this.

https://stackoverflow.com/questions/48344631/visual-studio-code-doesnt-show-latest-version-of-npm-packages-on-hover

**Comment by pflannery** [comment]
This looks similar to #122 

The solution from this comment ensures that package.json is always treated as a json file

https://github.com/vscode-contrib/vscode-versionlens/issues/122#issuecomment-493410952
