### ISSUE TITLE
0.26 broke support for unknown packages

### ISSUE THREAD

**Issue by matthieusieben** [vscode-contrib/vscode-versionlens#189]
Using a Lerna based mono repo with un-published packages:
```
- package.json
  { "workspaces": [ "packages/*" ] }
- packages/
  - a/package.json
     { "name": "@my-company/a", "version": "1.0.0" }
  - b/package.json
     { "name": "@my-company/b", "dependencies": { "@my-company/a": "^1.0.0" } }
```

With version `<= 0.25`, unknown packages were reported as `@my-company/a could not be found`. With version `>= 0.26`, code lens seems not to load at all.

**Comment by pflannery** [comment]
@matthieusieben This is fixed in 0.26.2. Let me know how it goes.
