### ISSUE TITLE
Package information text ends up at the wrong line (pubspec.yaml)

### ISSUE THREAD

**Issue by RCSandberg** [vscode-contrib/vscode-versionlens#193]
Hi,

Seems to be some already created issues related to versions 0.26 and later. 
I'm seeing the information text about the packages at the wrong line. 
Gets more messed up with added comments.

Attaching some screenshots.
Version 0.26.0 - text in the correct place for the found packages (but with the already reported problem with unknown packages)
![0 26 0](https://user-images.githubusercontent.com/18184100/81327703-fa2ff900-909b-11ea-8b7a-557b4f31b542.PNG)

Version 0.26.0 with some comments. You can see the "An error occured..." at wrong lines.
![0 26 0_with_comments](https://user-images.githubusercontent.com/18184100/81328287-f0f35c00-909c-11ea-82e0-ec38e5cfadbe.PNG)

0.26.1 (and 0.26.2 as well)- Text related to packages at the wrong lines
![0 26 1](https://user-images.githubusercontent.com/18184100/81328031-87734d80-909c-11ea-9268-40f40803b7bb.PNG)

BR,
Robert

**Comment by pflannery** [comment]
@RCSandberg These issues were fixed in 0.26.1. 

I was not able to recreate the issue you posted about 0.26.2.
Please update to the latest version which is now 0.27.0.

**Comment by RCSandberg** [comment]
Hi!

Tested 0.27.0, unfortunately same issue. Screenshot attached.

Let me know if there is anything I can do to assist.

![0 27 0](https://user-images.githubusercontent.com/18184100/81339742-f194ee00-90ae-11ea-9874-269f8774c65d.PNG)

VSCode version 1.45.0

**Comment by pflannery** [comment]
@RCSandberg  I cant seem to recreate can you provide an example pubspec ?

**Comment by RCSandberg** [comment]
@pflannery Sure! The one I'm using is attached (without the .txt of course).

[pubspec.yaml.txt](https://github.com/vscode-contrib/vscode-versionlens/files/4597600/pubspec.yaml.txt)

**Comment by pflannery** [comment]
@RCSandberg Im still not able to recreate

![image](https://user-images.githubusercontent.com/1727302/81427328-93214b80-9152-11ea-8752-f429ceb2f41e.png)

What OS are you using? 

Also in one of your images it seems to show a strange unicode character. I wonder if that is causing an issue?
![image](https://user-images.githubusercontent.com/1727302/81427461-c1069000-9152-11ea-8dba-b5d9b8db41c5.png)

**Comment by RCSandberg** [comment]
I'm on Windows 10 Pro, or as VSCode likes to call the OS: Windows_NT x64 10.0.18362

From VSCode:
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

The unicode character is just font ligatures. Some fonts have support for it and VSCode can pretty print them. It is a setting you can do in settings.json, "editor.fontLigatures": true
I set it to false, just to try. Same result.

![0 27 0_disabled_font_ligatures](https://user-images.githubusercontent.com/18184100/81434239-26b04780-9166-11ea-8c32-06fb6c57139c.PNG)

Something seems to have happened after 0.26, since that shows versions on correct line (though with the error message at flutter SDK.
![0 26 0_disabled_font_ligatures](https://user-images.githubusercontent.com/18184100/81434464-75f67800-9166-11ea-958a-2ea4eec5e0ae.PNG)

**Comment by bounty1342** [comment]
Hi,

I encounter the same issue on Mac OS on 0.27.0 :

```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

![image](https://user-images.githubusercontent.com/6307253/81460690-4025b380-91a7-11ea-94e8-febc4a3cba38.png)

Same pubspec works fine on 2.6.0.

**Comment by pflannery** [comment]
@bounty1342 
> Same pubspec works fine on 2.6.0.

Your example works for me on windows and ubuntu with vscode 1.45.0 and 0.27.0 

![image](https://user-images.githubusercontent.com/1727302/81463657-05297d00-91b3-11ea-8244-e4bd2fbaa659.png)

**Comment by bounty1342** [comment]
Does your plugin look at other files ? Pubspec.lock ?

I have the issue on 3 of my pojects. Since the very simple pubspec trigger it on my side but not on your, wonder if it might be configuration related.

**Comment by pflannery** [comment]
It only looks at the pubspec file with the [yaml](https://github.com/eemeli/yaml) parser

In the past I know that vscode has failed to upgrade versions even though it looks like it has upgraded. If you haven't can you try a clean install?

Remove the plugin folder at C:\Users\{{YourUserName}}\.vscode\extensions\pflannery.vscode-versionlens-0.27.0 and then re-install the extension

Otherwise im wondering if this is a BOM character issue or similar.

**Comment by avechuche** [comment]
I have the same problem, but I noticed the error appeared after updating to flutter 1.17. Maybe it was coincidence, or maybe that's the problem.

**Comment by pflannery** [comment]
if clean install doesnt work then can you try disabling all extensions and then only enable versionlens.

**Comment by avechuche** [comment]
> if clean install doesnt work then can you try disabling all extensions and then only enable versionlens.

Not :(. Still not working

**Comment by RCSandberg** [comment]
Tried a clean install, with and without all other extensions disabled. Unfortunately no difference.

**Comment by bounty1342** [comment]
Launching a new VS code with same pubspec works, but on all project created before it failed.
Did try the clean install with no success.

**Comment by CodeDoctorDE** [comment]
👍 
![image](https://user-images.githubusercontent.com/20452814/81645286-9d309c00-9429-11ea-83ab-4c7cae26cad0.png)
I have the same issue!

**Comment by CodeDoctorDE** [comment]
Windows 10

**Comment by pflannery** [comment]
I found the issue. 

The yaml parser doesnt include the the CRLF in the position output from the parser.
I will look at getting this fixed soon.

In the mean time if you click on the "End of line sequence" option in the bottom right of the editor you can switch to LF.

![image](https://user-images.githubusercontent.com/1727302/81811868-38ef0480-951d-11ea-9ac4-da59f47f0cc5.png)

**Comment by CodeDoctorDE** [comment]
works 👍
