### ISSUE TITLE
Extension uses deprecated GitHub API authorization method

### ISSUE THREAD

**Issue by vladfrangu** [vscode-contrib/vscode-versionlens#194]
Hello!

Firstly, thank you very much for creating this plugin, it helps a CRAP TON in keeping dependencies up to date if you want to manually update dependencies!

I thought I should bring up the following email I just re-received from GitHub:
![image](https://user-images.githubusercontent.com/17960496/82099468-1ffa7500-9710-11ea-83ef-a285de2c8555.png)

It seems like VersionLens doesn't use the new GitHub authorization method but rather an old one. Could this possibly be looked into? 

Thanks!

**Comment by pflannery** [comment]
1.0.0 is live now. This issue is now addressed
