### ISSUE TITLE
0.27 broke DotNet support

### ISSUE THREAD

**Issue by icleolion** [vscode-contrib/vscode-versionlens#195]
My csproj
`<ItemGroup>
    <PackageReference Include="ElmahCore" Version="1.2.5" />
    <PackageReference Include="ElmahCore.Sql" Version="1.2.5" />
    <PackageReference Include="EPPlus" Version="4.5.3.2" />
    <PackageReference Include="FluentFTP" Version="32.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.2.6" />
    <PackageReference Include="RoslynCodeTaskFactory" Version="2.0.7" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.7.0" />
  </ItemGroup>`

My DevTools Console
![image](https://user-images.githubusercontent.com/47498402/82101614-d6f0f380-9704-11ea-89c4-e59805dcce39.png)

**Comment by pflannery** [comment]
thanks for reporting this.

```xml
<PackageReference Include="Microsoft.AspNetCore.App"  />
```

I see why, it's missing `version` attribute. Will look to fixing the hard crash.

**Comment by pflannery** [comment]
1.0.0 is live now. These issues should be addressed

**Comment by icleolion** [comment]
Sorry to say, this is still broken, in fact, everything is broken!  Not getting anything meaningful in dev console anymore.  I don't see anything in VersionLens output log either, but I do get the following in the Log (Extension Host) output:
![image](https://user-images.githubusercontent.com/47498402/82553840-ba1d4b80-9b5c-11ea-9a51-95cce302dfaf.png)

**Comment by pflannery** [comment]
is that using the same PackageReferences as you posted in the first comment? I see this 

![image](https://user-images.githubusercontent.com/1727302/82606359-d944c900-9bae-11ea-92f9-c579ff035e8e.png)

I did however see another issue with broken xml but I cant recreate what you see yet.

**Comment by icleolion** [comment]
Correct, nothing has changed for my PackageReferences.  Not sure if it's relevant but the changelog states you are now using the output of the CLI command `dotnet nuget list source`.  My dotnet cli doesn't have that command.
![image](https://user-images.githubusercontent.com/47498402/82614086-e1a50000-9bbe-11ea-8193-8fa67d0cf0f2.png)

**Comment by icleolion** [comment]
So i'm going to assume you are on nuget cli v5.5 and above.
https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.5

I'm still stuck on VS 2017.  With VS Code proving to be a capable IDE, my business isn't interested in moving to VS 2019.

**Comment by pflannery** [comment]
> So i'm going to assume you are on nuget cli v5.5 and above.
> https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.5

I totally missed that thanks.

**Comment by icleolion** [comment]
Saw changelog for 1.0.1, was really hopeful this would be the version for me!

Unfortunately it's stuck installing!

![image](https://user-images.githubusercontent.com/47498402/82644774-c7dcda80-9c09-11ea-857e-c7b12fd7c073.png)

**Comment by icleolion** [comment]
Manual install works fine however, and I can confirm 1.0.1 has fixed my issue!
