### ISSUE TITLE
Nuget client does not support http url's

### ISSUE THREAD

**Issue by Hoffs** [vscode-contrib/vscode-versionlens#200]
Sure everything should use https, but some internal sources are only available using http. As far as I can see this filters out to only use https. Is this just because or is there some concrete reason for only https?

https://github.com/vscode-contrib/vscode-versionlens/blob/853fe3adbebaf9bb45859d19bb0104c017ad8d5b/src/infrastructure/providers/dotnet/dotnetProvider.ts#L64
```
      s => s.protocol === RegistryProtocols.https
```

**Comment by pflannery** [comment]
this is fixed in v1.0.1. Im going to close
