### ISSUE TITLE
Https sources with incomplete self signed certificate chain fails

### ISSUE THREAD

**Issue by Hoffs** [vscode-contrib/vscode-versionlens#201]
When using https source that is setup using self signed certificates but with invalid certificate chain the request fails with an error: "Error: unable to verify the first certificate". Because http sources are not supported ( #200 ) and because there are no flags for controlling http client ssl check (e.g. https://github.com/microsoft/node-request-light/blob/master/src/main.ts#L32 ) this leads to the extension being unusable. 

So it would be nice to have an option to control SSL strictness or something.

**Comment by pflannery** [comment]
This should be fixed in v1.0.0 by setting the strictSSL option

`versionlens.http.strictSSL` or `versionlens.{provider}.http.strictSSL.`

**Comment by pflannery** [comment]
Closing this as the fix is released.
