### ISSUE TITLE
Change in behaviour for "latest" between 0.27.0 & 1.0.0

### ISSUE THREAD

**Issue by icleolion** [vscode-contrib/vscode-versionlens#206]
0.27.0
![image](https://user-images.githubusercontent.com/47498402/82614578-19607780-9bc0-11ea-8cdd-aeca3f9d4693.png)
Nothing to do here.  Latest is rendered for information purposes only.  All good.

1.0.0
![image](https://user-images.githubusercontent.com/47498402/82614660-4d3b9d00-9bc0-11ea-82ad-bec09cc100b8.png)
Now it seems to be picking up a later version, so `latest` is now clickable, but doing so then results in this:
![image](https://user-images.githubusercontent.com/47498402/82614699-69d7d500-9bc0-11ea-993d-71c57cffd78f.png)

**Comment by pflannery** [comment]
> 1.0.0
> ![image](https://user-images.githubusercontent.com/47498402/82614660-4d3b9d00-9bc0-11ea-82ad-bec09cc100b8.png)
> Now it seems to be picking up a later version, so `latest` is now clickable, but doing so then results in this:
> ![image](https://user-images.githubusercontent.com/47498402/82614699-69d7d500-9bc0-11ea-993d-71c57cffd78f.png)

It should show a down arrow on the latest suggestion. I havent quite got to re-implementing that case yet though.

**Comment by pflannery** [comment]
> It should show a down arrow on the latest suggestion. I havent quite got to re-implementing that case yet though.

The other case is when a package has not releases but only has prereleases. Thats an edge case on my todo list

**Comment by pflannery** [comment]
This is resolved in [1.0.6](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#106)

**Comment by pflannery** [comment]
1.0.7 is now released too so will close. thanks for reporting
