### ISSUE TITLE
Private github packages no longer working

### ISSUE THREAD

**Issue by willyjfarrell** [vscode-contrib/vscode-versionlens#210]
Private packages in `package.json` are no longer found. In v0.27, after adding my github access token, it would find private packages, but would only show the latest commit-ish for each package. I was looking forward to the semver support that was added, but now my private packages are no longer found.

I have to blur the actual package names, as they are internal to my company. 

**v0.27**
![versionlens-issue-1](https://user-images.githubusercontent.com/4080733/82627661-82d88a00-9bb0-11ea-97ee-8fa4abb6aac7.png)

**v1.0.0**
![versionlens-issue-2](https://user-images.githubusercontent.com/4080733/82627664-83712080-9bb0-11ea-8675-4bfc6bb18a8f.png)

None of my config settings changed between the versions.

**Comment by pflannery** [comment]
Im guessing it's related to this change https://github.com/vscode-contrib/vscode-versionlens/issues/194

I don't have private github repo's to test but I use a token to increase my rate limit.

**Comment by pflannery** [comment]
ok so I'm going to take this chance to update this older method of authenticating github with credentials. It's also a chance to provide other http request services with additional header data too.

What im going to build is a configurable method of setting individual endpoint credentials with fallbacks...so in your case github can be used like this in the contributions

```jsonc
"versionlens.http": {
  "//api.github.com/repos": {
    // http headers
    "Authorization": "token {{github-token}}"
  },
  "//api.github.com/repos/user/project": {
    // http headers
    "Authorization": "token {{specific-project-token}}",
  },
}
```

You can then decided to have just one auth entry for easy access or you can specify individual endpoints with different authorizations. Its a bit like how .npmrc file works but using json.
Hoping to get this complete this week.

At some point in the future I would also like to use github web authentiation once vscode protocol api is out of preview.

**Comment by pflannery** [comment]
I found out that it wasnt actually passing the auth token to github. 

Have now ensured it's passed in. This doesnt implment the work I still want to do ( see previous comments) 

[You can install the preview of this fix here](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.7-preview.2)

**Comment by willyjfarrell** [comment]
Working perfectly! Thank you!

**Comment by pflannery** [comment]
1.0.7 is now released so will close. thanks for reporting.
