### ISSUE TITLE
Weird behaviour with 4-segment versions returning "no match"

### ISSUE THREAD

**Issue by icleolion** [vscode-contrib/vscode-versionlens#214]
A gif is worth a thousand words.  No real pattern to what I'm seeing.  It's just really hit and miss as to whether the versionlens works for the EPPlus package.
![peek](https://user-images.githubusercontent.com/47498402/82670054-60885000-9c34-11ea-8443-8f62ae6af6e6.gif)

**Comment by pflannery** [comment]
I see what that is. Its related to 4 segment versions. Versionlens only supports semver.

4 segment versions were removed due to https://github.com/vscode-contrib/vscode-versionlens/issues/169

It seems that they are appearing in some cases.

**Comment by icleolion** [comment]
Oh I thought the `no match | latest 5.1.2` was the expected output, and that it randomly failing was bug, but you're saying it's the other way around?  Would it be possible to have VersionLens when it sees a 4 segment version skip attempts to match, and just return the latest (e.g. exactly like it's sometimes doing now), so I can continue to use this extension to alert me to updates without having to keep tabs on repositories?

**Comment by pflannery** [comment]
4 segment versions just isnt supported.

**Comment by pflannery** [comment]
In order to find the latest version in a list of mixed semver and 4 segment versions versionlens would need it's own seperate version parser to correctly compare.

**Comment by pflannery** [comment]
Using published dates would not solve this either, consider this scenario 

The author has a library that has an LTS (long term support) version. Let's say v1.8.
Their current release is v2.0.1.1. The author publishes a patch for v1.8.7.1.
If versionlens used published dates then the latest 'published' version is not actually the current release.

Would be happy to use 'solid' parser (like semver) if one exists.

**Comment by icleolion** [comment]
> The author has a library that has an LTS (long term support) version. Let's say v1.8.
> Their current release is v2.0.1.1. The author publishes a patch for v1.8.7.1.
> If versionlens used published dates then the latest 'published' version is not actually the current release.

Ah, indeed something I hadn't taken into account.  Which is annoying considering the package I update most thanks to Version Lens bringing it to my attention is Vuetify, which has an LTS version. https://www.npmjs.com/package/vuetify?activeTab=versions

Shame you can't rely on dist-tags being used properly either.

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/214
