### ISSUE TITLE
Prereleases not being picked up.

### ISSUE THREAD

**Issue by icleolion** [vscode-contrib/vscode-versionlens#216]
![image](https://user-images.githubusercontent.com/47498402/82694577-647b9880-9c5b-11ea-8166-443a35282613.png)

https://github.com/vuetifyjs/vuetify/releases

I'm expecting v2.3.0-beta.6 to be picked up.

**Comment by pflannery** [comment]
This is fixed in [v1.0.3](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.3)

**Comment by icleolion** [comment]
Thanks, not only can I confirm this is working, but compared to 0.25.0: 
![image](https://user-images.githubusercontent.com/47498402/82737929-226e5780-9d2c-11ea-8191-c9fa2aa602a7.png)


1.0.3 I would say is a great improvement:
![image](https://user-images.githubusercontent.com/47498402/82737926-1c787680-9d2c-11ea-9e48-537da9299786.png)
