### ISSUE TITLE
infinite update loop

### ISSUE THREAD

**Issue by yumetodo** [vscode-contrib/vscode-versionlens#218]
When I install this plugin, my vscode tries to update this plugin's version infinitely.
It's a related issue I think that on [the visual studio marketplace](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens), this plugin's latest version is 1.0.0. However, on Github Release, 1.0.3.
![image](https://user-images.githubusercontent.com/10869046/82724562-e3330d00-9d11-11ea-967b-ac780184a8b7.png)

See this movie( https://youtu.be/HIVVyTCOo7Y ). 

Re-instal, install from vsix or PC restart has no effect.

Due to this issue, CPU usage is always around 70%.

cpu: Intel Core i7-7500U
RAM: 16GB

**Comment by icleolion** [comment]
duplicate of https://github.com/vscode-contrib/vscode-versionlens/issues/211

**Comment by yumetodo** [comment]
Oh, I missed it. close.
