### ISSUE TITLE
Exclude project references in project.json

### ISSUE THREAD

**Issue by jp7677** [vscode-contrib/vscode-versionlens#22]
Project.json also supports project references like:

```
"MyOtherLibrary": {
      "version": "0.1.0",
      "target": "project"
    },
```

Your extension tries to find a version on nuget and obviously fails with a Error 404. Dependencies with target "project" should be excluded.

**Comment by pflannery** [comment]
project.json is not supported anymore and this project now supports the newer csproj xml format.
