### ISSUE TITLE
Use Webpack to bundle and minify 

### ISSUE THREAD

**Issue by badre429** [vscode-contrib/vscode-versionlens#226]
Use Webpack to bundle and minify its sources. Using webpack will help to reduce the install- and startup-time of large extensions because instead of hundreds of files, a single file is produced.

**Comment by pflannery** [comment]
I have tried several rollup libs.
webpack cant handle some of the npm modules that are being used by this project and it ends up with a node modules folder anyway. 

The closest I got so far is using browserify with --node option. I will give it another stab at some point. But at the moment Im focusing on a clean architecture which is turn will make it independent from node modules and let me drop 'mock-require' in unit tests

**Comment by pflannery** [comment]
At that point I will focus on the packing side of this project...
for now its not too shabby and works well enough so it's not a priority

**Comment by badre429** [comment]
@pflannery  i can try to make pull request integrating webpack build

**Comment by pflannery** [comment]
> @pflannery i can try to make pull request integrating webpack build

Thanks for the offer but not just yet. 

I'm moving each domain\area to seperate nested projects much like a typical dotnet repo or lerna repo. Im doing it bit by bit while still delivering fixes and some addtional minor features.

Keeping this open until then...
