### ISSUE TITLE
Latest version of cheerio not being picked up

### ISSUE THREAD

**Issue by Tsuk1ko** [vscode-contrib/vscode-versionlens#230]
I'm using v1.0.4 installed via VSIX.

It is similar to #216

![image](https://user-images.githubusercontent.com/24877906/82746163-58a8e700-9dbf-11ea-8ea0-65a2c90e37f7.png)

![image](https://user-images.githubusercontent.com/24877906/82746115-c1dc2a80-9dbe-11ea-8d4a-5cc0b586b3d6.png)

**Comment by icleolion** [comment]
I’m not familiar with the codebase, but the i’m guessing dist tags aren’t taken into account and to be honest I prefer the way this has been picked up. If the dist tags were strictly adhered to, then all you would get is the rc.3 release, but I appreciate having one-click access to the latest stable release which is 0.22.0. If cheerio consider rc.3 to be stable then really they should release a proper v1.

**Comment by Tsuk1ko** [comment]
@icleolion Oh, I think you are right.

I didn't notice that there is a setting "Show Prereleases On Startup".
