### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by SteveALee** [vscode-contrib/vscode-versionlens#237]
It's stuck in an install loop between "intalling" and "update to version 1.0.4"

I tried installing from the command line but still get the loop when I enter code.

I have the latest code. tried rebooting etc.

**Comment by LeanderD** [comment]
Same here!

**Comment by LeanderD** [comment]
Fixed it by installing it manually:
`code --install-extension vscode-versionlens-1.0.4.vsix`

See releases page: [Versionlens Releases](https://github.com/vscode-contrib/vscode-versionlens/releases)

**Comment by jamesmosier** [comment]
Looks to be a duplicate of https://github.com/vscode-contrib/vscode-versionlens/issues/211

**Comment by pflannery** [comment]
> Looks to be a duplicate of #211
