### ISSUE TITLE
npm's with local paths gives error

### ISSUE THREAD

**Issue by mmc41** [vscode-contrib/vscode-versionlens#24]
If I add a reference to a [local filesystem npm package](https://docs.npmjs.com/files/package.json#local-paths), version lens incorrectly does a lookup in the central registry and subsequently gives an error.. Instead it should just ignore any version references of format "file: ...". I suspect git references could be a problem too (but have not tried it).

**Comment by mmc41** [comment]
Thanks for the fix. I can confirm it works fine now! :-)

**Comment by xnnkmd** [comment]
@pflannery While this fix worked for local references, it still fails for git references like this: 
`"@myscope/mypackage": "git+https://mypath",`
