### ISSUE TITLE
Versionlens no longer doing anything at all

### ISSUE THREAD

**Issue by robross0606** [vscode-contrib/vscode-versionlens#240]
I have the latest version available (1.0.6).  I open my pacakge.json file and it no longer shows lens info.  I edited my settings to bump logging up to verbose.  The output tab shows this:
```
2020-05-26 18:48:05 info extension: version: 1.0.6
2020-05-26 18:48:05 info extension: log level: verbose
2020-05-26 18:48:05 info extension: log path: c:\Users\user\AppData\Roaming\Code\logs\20200526T184749\exthost1\pflannery.vscode-versionlens
```
However, navigating to this directory shows no such file.  There is no "verbose" logging output anywhere.

**Comment by icleolion** [comment]
1.0.6 defaults to version lens being turned off, you need to click the V in the top right corner to fire it up.

**Comment by pflannery** [comment]
> I have the latest version available (1.0.6). I open my pacakge.json file and it no longer shows lens info. I edited my settings to bump logging up to verbose. The output tab shows this:
> 
> ```
> 2020-05-26 18:48:05 info extension: version: 1.0.6
> 2020-05-26 18:48:05 info extension: log level: verbose
> 2020-05-26 18:48:05 info extension: log path: c:\Users\user\AppData\Roaming\Code\logs\20200526T184749\exthost1\pflannery.vscode-versionlens
> ```
> 
> However, navigating to this directory shows no such file. There is no "verbose" logging output anywhere.

Can you set the logging level to `debug`
Its called `versionlens.logging.level` under `Extension->VersionLens` in your settings

**Comment by jordanthomas** [comment]
1.0.6 doesn't seem to do anything for me either - reporting all packages as "latest" despite new versions being available.

Rolled back to 1.0.0 and it started displaying the available versions again.

**Comment by pflannery** [comment]
@jordanthomas did u try setting `versionlens.caching.duration` to 0? it defaults to 3 minutes.

**Comment by SleeplessByte** [comment]
Is it possible that the upgrade path wasn't clean?

```
[2020-05-28 19:47:03.842] [sharedprocess] [error] Failed to install extension: pflannery.vscode-versionlens Cannot read property 'isDefault' of undefined
```

**Comment by jordanthomas** [comment]
@pflannery No I did not - I'll give it a shot.

**Comment by pflannery** [comment]
@SleeplessByte 

> Is it possible that the upgrade path wasn't clean?
> 
> ```
> [2020-05-28 19:47:03.842] [sharedprocess] [error] Failed to install extension: pflannery.vscode-versionlens Cannot read property 'isDefault' of undefined
> ```

I've not had your issue myself.  I just did a reinstall and it worked...also tested it by removing the versionlens extension folder from `{home}/.vscode/extensions`

There isn't a 'isDefault' property in this project. Looks like a vscode issue

**Comment by jordanthomas** [comment]
Here's what I'm seeing w/ 1.0.6.

![Screen Shot 2020-05-28 at 2 04 23 PM](https://user-images.githubusercontent.com/301890/83177205-a473cd00-a0ec-11ea-997e-0a126e180a7f.png)

**Comment by pflannery** [comment]
> Here's what I'm seeing w/ 1.0.6.
> 
> ![Screen Shot 2020-05-28 at 2 04 23 PM](https://user-images.githubusercontent.com/301890/83177205-a473cd00-a0ec-11ea-997e-0a126e180a7f.png)

@jordanthomas  ah I see the problem. It should say `satisifes latest 7.10.1` as the `^` means include minor updates which will actually install the latest version in this case!

When I remove the range symbol I see this.

![image](https://user-images.githubusercontent.com/1727302/83177482-0ea16780-a117-11ea-94a3-e0549a576a24.png)

Can you open a new issue for this?

**Comment by jordanthomas** [comment]
[Sure!](https://github.com/vscode-contrib/vscode-versionlens/issues/248)

**Comment by pflannery** [comment]
closing this as OP never responded and I cant recreate.
