### ISSUE TITLE
JsonPackageParser not able to go deeper then one level

### ISSUE THREAD

**Issue by Razzeee** [vscode-contrib/vscode-versionlens#241]
Is there a way to let the parser go deeper? I just need two levels. A config like `dependencies.indirect` would be great. I don't think this is possible yet?

Especially due to this?
https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/core/packages/parsers/jsonPackageParser.ts#L38

**Comment by pflannery** [comment]
No I dont think that would be possible in the current setup. 

I'm currently working on something similar for configuration that is similar to the behaviour you require. Its got me wondering if it could be used with parsers too.

**Comment by Razzeee** [comment]
I guess I can wait for that to land. If you need anything from me, let me know.

**Comment by pflannery** [comment]
> I guess I can wait for that to land. If you need anything from me, let me know.

Do you have an example of the json of `dependencies.indirect` ?

**Comment by Razzeee** [comment]
Sure, there are these two docs describing the files:
https://github.com/elm/compiler/blob/master/docs/elm.json/application.md
and
https://github.com/elm/compiler/blob/master/docs/elm.json/package.md

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/241
