### ISSUE TITLE
New versions not discoverable when dependency is satisfied

### ISSUE THREAD

**Issue by jordanthomas** [vscode-contrib/vscode-versionlens#248]
VersionLens 1.0.6 shows "latest" for dependencies that are satisfied, even if a newer release is available.

![versionlens-1 0 6](https://user-images.githubusercontent.com/301890/83178028-f6692280-a0ed-11ea-9e91-18abdab71c3f.png)

[Related comment from @pflannery over here.](https://github.com/vscode-contrib/vscode-versionlens/issues/240#issuecomment-635512897)

**Comment by pflannery** [comment]
@jordanthomas 

A fix for this is in the [1.0.7-preview.3 build](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/1.0.7-preview.3)

**Comment by pflannery** [comment]
1.0.7 is now released so will close. thanks for reporting
