### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by bialad** [vscode-contrib/vscode-versionlens#25]
I find this extension immensely useful, and use for both node and .Net projects. So far I've been running Windows 10, and it has worked well.

I'm now running Ubuntu 16.10, with vs code 1.7.1 installed. And your extension is not showing anything anymore. I'm not getting any errors, it just doesn't show any versions in either package.json or project.json, for any folders.

I downloaded the repository from github to troubleshoot, but to my surprise it works when I run it in a development host. Any ideas about what could cause this, or how I can troubleshoot a "live" host?

node -v -> v6.9.1
npm -v -> 3.10.9

**Comment by WebFreak001** [comment]
Works for me on linux, can't confirm. Try changing the side of the menu at the left to the right and then its maybe #23

**Comment by pflannery** [comment]
just tested latest version on ubuntu 16.04 and its working

![image](https://cloud.githubusercontent.com/assets/1727302/20251534/c2563414-aa11-11e6-98f8-d5b1613262fd.png)

@bialad can you try removing the extension from ~/.vscode/extensions/ and re-installing?

**Comment by jp7677** [comment]
The extension works just perfectly on my Fedora 24 box...

**Comment by bialad** [comment]
I never got the change to try a reinstall off version 0.8.0, because now that 0.10.0 was released it works.

@pflannery If nothing was done to actively address this issue, i guess an update is the same as a reinstall and that cured it.
