### ISSUE TITLE
Colours - Unknown Configuration Settings

### ISSUE THREAD

**Issue by rfgamaral** [vscode-contrib/vscode-versionlens#252]
It seems these configuration options have been deprecated:

![image](https://user-images.githubusercontent.com/96476/83327073-1543f200-a271-11ea-8e1d-e38bb75e028d.png)

I've searched the README and CHANGELOG and can't find anything related to this change. Code's Intellisense also doesn't seem to show anything related to color personalization. I have [found this](https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/presentation.extension/src/options/statusesOptions.ts) in the source but they don't show up in Code's Intellisense either.

Have they been removed?

**Comment by pflannery** [comment]
@rfgamaral the outdated feature is what uses the colour options. The feature has been disabled for the time being [noted in 1.0.0 changelog (last entry)](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#100)

**Comment by rfgamaral** [comment]
I feel like that description was a bit vague so that's why I probably missed it. Thanks for the clarification. Hope to see this reimplemented in the future. Stay safe.

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/252
