### ISSUE TITLE
Improve icons for better consitency with Code's UI

### ISSUE THREAD

**Issue by rfgamaral** [vscode-contrib/vscode-versionlens#253]
This is how VersionLens icons currently look:

![image](https://user-images.githubusercontent.com/96476/83327341-d57e0a00-a272-11ea-9b01-57433f49f685.png)

![image](https://user-images.githubusercontent.com/96476/83327278-5ee10c80-a272-11ea-969c-a2735de8433c.png)

As you can see there are a few inconsistencies with Code's UI:

- VersionLens icons are a bit bigger than Code's;
- VersionLens icons are not properly aligned;
- VersionLens icons are not properly spaced out.

I know this is a very small and probably low priority issue but would love to see this fixed.

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/253
