### ISSUE TITLE
Support private npm registry

### ISSUE THREAD

**Issue by unional** [vscode-contrib/vscode-versionlens#26]
Can you read `npm get registry` and read from it? That will enable support of private npm registry.

🌷

**Comment by pflannery** [comment]
Duplicate of https://github.com/vscode-contrib/vscode-versionlens/issues/15 ?
We switched to use the npm node library in version 0.8.0 which supports private registries

Which version are you using?

**Comment by unional** [comment]
Private Package is different. You are still fetching from `https://registry.npmjs.org/`, correct?

This is about configuring to fetch on a different server, e.g. `https://npm.mycompany.local:1234`.

User (company-wide) configure which npm registry to use by:

1. Setting up the npm enterprise service.
2. Configure local npm with `npm set registry https://npm.mycompany.local:1234`.

I'm using 0.6.0. There is a 0.8.0?
Didn't get any update from VSC extension manager.

**Comment by unional** [comment]
Strange. I search for it and then see 0.8.0. Didn't get notify to update from 0.6.0

**Comment by unional** [comment]
Oh, nice. After upgrading it is working. So the node library you use does support private registry. 🌷

**Comment by pflannery** [comment]
@unional yes the npm library used is the official library https://github.com/npm/npm

> (Should read your comment more carefully. #15 OP was about private package.)

Actually it became both private package and private registry. https://github.com/vscode-contrib/vscode-versionlens/issues/15#issuecomment-254428965
