### ISSUE TITLE
VersionLens fails if nuget package source fails

### ISSUE THREAD

**Issue by bigred8982** [vscode-contrib/vscode-versionlens#262]
I have some old private nuget repositories that cause two major problems for VersionLens. When either of these happen, VersionLens is essentially dead until I manually (and temporarily) resolve sources list.

1) The nuget source is unreachable - in my case, they require a VPN to access and sometimes I'm just not connected to it
2) Some of the private repos are using v2

I'd like VersionLens to "do it's best", which in my mind means that when it can't resolve the nuget source, it will just ignore that and continue to work with what it has.

Version 1.0.7

**Comment by pflannery** [comment]
this fix is now released in [1.0.8](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#108)
