### ISSUE TITLE
Version Lens doesn't load

### ISSUE THREAD

**Issue by nZeus** [vscode-contrib/vscode-versionlens#264]
It says the extension is _enabled_, but in fact, it doesn't work:
* button is not present when I open package.json file:
![image](https://user-images.githubusercontent.com/2727326/84398590-6ef8d480-ac00-11ea-8b19-c4499d3b8e59.png)

* It doesn't generate any output:
![image](https://user-images.githubusercontent.com/2727326/84398347-1e817700-ac00-11ea-9fa1-411b52a1d4c6.png)

* When I search for `Version Lens` commands, I see this one:
![image](https://user-images.githubusercontent.com/2727326/84398675-8768ef00-ac00-11ea-8d0d-af7245004cb9.png)
but it doesn't work:
![image](https://user-images.githubusercontent.com/2727326/84398293-10335b00-ac00-11ea-82fa-25c6a64d4e0f.png)

**Comment by pflannery** [comment]
Which version did this occur?

Have you tried doing a clean install? https://github.com/vscode-contrib/vscode-versionlens#im-not-able-to-install-this-extention

**Comment by daraclare** [comment]
I have the same issue, I just tried a clean install as advised above, but no change. Versions are not showing for me although the extension (v1.0.8) looks to be installed. On VSCode Version: 1.46.0.

**Comment by gregoranders** [comment]
Hi

```sh
node --version
v14.4.0

Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.15-gentoo
```

same issue here, Gentoo Linux so it might be a reason, anyway I get the icons only after the initial (manual) fresh install (wiping .vscode folder and configs) but only the icons, extension as such does not work already at this moment as it does not show the versions. CTRL+P -> version states there has been an error, but infact there is nothing in the logs all I get is the same error message as already posted. Not an expert on NodeJS but I noticed the different NodeJS versions...I use 0.14x

**Comment by gregoranders** [comment]
For the reason it failed on my side, I had the following in the settings.json of my vscode configuration. Removing it fixes the issue. It is recommended by the api-extractor docs so you might run into it in the future.

```json
  "files.associations": { "*.json": "jsonc" }
```

**Comment by Moeriki** [comment]
Version lens doesn't load for me either.

These are my settings.
https://gist.github.com/Moeriki/39f588300066cc37dd42a6cf7b060402

The last version of version lens that works for me is 0.27.0.

**Comment by pflannery** [comment]
> For the reason it failed on my side, I had the following in the settings.json of my vscode configuration. Removing it fixes the issue. It is recommended by the api-extractor docs so you might run into it in the future.
> 
> ```json
>   "files.associations": { "*.json": "jsonc" }
> ```
> 
> Fix:
> 
> ```json
>  "files.associations": { "*.json": "jsonc", "package.json": "json" }
> ```

Yes as discussed here #122

**Comment by pflannery** [comment]
@Moeriki

> Version lens doesn't load for me either.

strange. 

Which provider? is it npm?

do you see the icons appear when you open the package\project file?

**Comment by Moeriki** [comment]
Oh I see. I never noticed there was a toggle. My bad! I think the lens was enabled by default before. Thanks, all is good!

**Comment by nZeus** [comment]
> Have you tried doing a clean install? vscode-contrib/vscode-versionlens#im-not-able-to-install-this-extention

I just tried the clean install as described in the article.
Stil the same, no changes.

I also set `versionlens.logging.level` to `debug`, restarted the VSCode, but it doesn't help...

![image](https://user-images.githubusercontent.com/2727326/85228368-5e581380-b3e3-11ea-9080-ee76f30058a9.png)

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/264
