### ISSUE TITLE
Support github locations for npm and jspm.

### ISSUE THREAD

**Issue by jp7677** [vscode-contrib/vscode-versionlens#28]
Jspm dependencies can look like:

```
"bootstrap": "github:twbs/bootstrap@~3.3.7",
"fetch": "github:github/fetch@~1.0.0",
```
Would be nice if your extension would support these. guess the implementation would be quite similar to the current nuget one. The git tags can be obtained using https://api.github.com/repos/:user/:repos/tags or even better https://api.github.com/repos/:user/:repos/releases where one can see the difference between release and pre-release.

E.g.
https://api.github.com/repos/twbs/bootstrap/releases
https://api.github.com/repos/twbs/bootstrap/tags

**Comment by pflannery** [comment]
I would like this to happen. Covering jspm and npm. 
I've been reorganising the project in preparation for this feature and #13 feature 
So far I've got the dependencies to show a clickable link to the github repo.

The next step is to determine the latest releases or tags or commits, falling back to commits if nothing else.
Will also need a setting that lets us choose the order in which is matched first between releases, tags and commits or even opt out of this feature all together defaulting to a basic clickable link to the source.

The github api could be useful but I'm going to look at the best node library so it can also work with other local\external git providers.

**Comment by pflannery** [comment]
also need to figure out private registries and packages

**Comment by pflannery** [comment]
Scrapped the last comment :). Meant authentication for private git repo's etc..

**Comment by jp7677** [comment]
Very cool, thanks a lot for your work!
