### ISSUE TITLE
Version numbers appear outside of the screen

### ISSUE THREAD

**Issue by shlomiborovitz** [vscode-contrib/vscode-versionlens#29]
When using version-lense the version status appear almost entirely outside of the screen
![image](https://cloud.githubusercontent.com/assets/12827864/20259585/64896598-aa5e-11e6-9ddb-0fe928389468.png)

**Comment by pflannery** [comment]
@shlomiborovitz this looks like a duplicate of #23. 

What version of vscode are you running? this should be fixed in the latest version
Can you check your zoom settings?

**Comment by shlomiborovitz** [comment]
@pflannery 
You're right, and I'm still in 1.7.
