### ISSUE TITLE
Question: How to specify jspm dependencies section in VS Code settings.

### ISSUE THREAD

**Issue by jp7677** [vscode-contrib/vscode-versionlens#35]
Hi there,

With https://github.com/vscode-contrib/vscode-versionlens/commit/8a853adfeaf713550b00d39c96713782b5d65e91 one can extend the npm section where versionlens looks for updates. How would I do that with the dependency subsections within jspm?
```
"versionlens.npm.dependencyProperties": [
   "jspm"
]
```
works ok, but then other jspm settings like configFile will also be parsed and that results in "Resource not found". I tried something like:

```
"versionlens.npm.dependencyProperties": [
   "jspm.dependencies",
   "jspm.devDependencies",
]
```
but that didn't worked.

Thanks in advance for your thoughts!

**Comment by eamodio** [comment]
Not sure if this is exactly related, but the codelens no longer shows up for jspm dependencies

**Comment by pflannery** [comment]
@eamodio Thanks. This is [fixed](https://github.com/vscode-contrib/vscode-versionlens/commit/9d176bf25df15889963ce07b2ad8170e28bfae70) in 0.12.1 

There isnt a way to set jspm dependency entries in the config as of yet but will add this in the near future

**Comment by jp7677** [comment]
Version 0.12.1 is perfectly fine again for jspm usage, thanks!
