### ISSUE TITLE
Show version data to right, not newline above.

### ISSUE THREAD

**Issue by replete** [vscode-contrib/vscode-versionlens#40]
The functionality of this package is excellent.

But I've stopped using it for two reasons:

* Editing the same file causes these 'version lines' to reflow, which is jarring and distracting. 
* The version line is high contrast and makes scanning for the line I'm interested in changing more difficult.

I think if these two issues were addressed, this would be an essential vscode package.

**Comment by pflannery** [comment]
@replete 

> Editing the same file causes these 'version lines' to reflow, which is jarring and distracting.

Yeah I agree its bit jarring especially at first (but I've gotten used to it)
This is something vscode controls. It happens when the json breaks. 

> The version line is high contrast and makes scanning for the line I'm interested in changing more difficult.

What theme do you use? I use a dark theme (Monokai) which doesn't interfere for me

**Comment by replete** [comment]
If it possible to move it to the right, I think it's a clear improvement: 
* no reflows
* version numbers closer in proximity
* contrast/legibility of text no longer an issue

Just the default Dark+ theme:
![image](https://cloud.githubusercontent.com/assets/812139/21814240/90f137fe-d750-11e6-8fe9-13c8eb3333b6.png)

**Comment by eamodio** [comment]
@replete As @pflannery mentioned, this isn't something that can be changed -- vscode controls how/when/where the CodeLens are rendered. All an extension can really do is say which lines should have CodeLens and what the content is.

**Comment by replete** [comment]
@eamodio But your GitLens extension does this? Is it an AST thing with JSON files or something?

**Comment by replete** [comment]
@pflannery I mean, it's worse than jarring really because it really gets in the way of working on the file...

**Comment by eamodio** [comment]
@replete GitLens provides an "annotation" to the right side, but the bit caveat with that is it isn't clickable (as it isn't a CodeLens which affords the click action). That alone feels like a deal-breaker, but another caveat with the "annotation" style is there really isn't a reasonable way to get it to progressively come into view (GitLens only computes a single line at a time) -- they would all have to be applied up front -- where via CodeLens they are dynamically evaluated making the performance much better.

**Comment by obambrough** [comment]
eamodio's Git Lens extension has a nice CodeLens toggle option - I think it would work well here too, so you'd only get the CodeLens (and reflow) if you toggle it on.

**Comment by pflannery** [comment]
@obambrough Can you open a new issue for that? as this is about placing code lenses on the right hand side

Until vscode supports placing code lenses to the right then there is no solution for this. Will need to get MS to reopen microsoft/vscode#22127. If that happens will be happy to implement this feature (if need be)
Will close this until that day if ever comes
