### ISSUE TITLE
git is not installed or not in the PATH

### ISSUE THREAD

**Issue by ajsb85** [vscode-contrib/vscode-versionlens#42]
Hi @pflannery

Can you use the same git binary used in the VS Code instead the git in the PATH?

![image](https://cloud.githubusercontent.com/assets/663460/22198985/39b7567c-e159-11e6-89ed-eb91d255080c.png)

---

- VSCode Version: Code - Insiders 1.9.0-insider (882244ea24cb0b89a9a0c6c649c8f857fb0bc408, 2017-01-23T07:12:16.134Z)
- OS Version: Windows_NT ia32 10.0.15014
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.2|
|ghlink|dt|0.0.5|
|EditorConfig|EditorConfig|0.3.4|
|Theme-Zenburn|gerane|0.0.3|
|sass-lint|glen-84|0.0.3|
|vscode-commitizen|KnisterPeter|0.3.5|
|vscode-github|KnisterPeter|0.9.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|vscode-docker|PeterJausovec|0.0.11|
|vscode-versionlens|pflannery|0.12.1|
|gitlink|qezhu|0.1.1|
|sass-indented|robinbentley|1.3.0|
|sharecode|RolandGreim|0.4.0|
|vscode-gtm|s3ramsay|0.1.2|
|gitflow|vector-of-bool|1.0.0|
|github-detial-comment|wk-j|0.0.9|

**Comment by WebFreak001** [comment]
@pflannery so just use `vscode.workspace.getConfiguration("git").get("path", "git")` instead of `"git"`

**Comment by pflannery** [comment]
@ajsb85 
strange, this plugin doesn't call git.

Are you looking at a bower.json file? if so what happens when you run `bower info angular` in a cli at the root of your workspace folder?

**Comment by ajsb85** [comment]
Hi @pflannery 

`bower ENOGIT git is not installed or not in the PATH`

![image](https://cloud.githubusercontent.com/assets/663460/22327264/a2ccf572-e3b6-11e6-9c61-d859c22ba1d4.png)

I was added the GitHub binary to the path env.

Salut.
