### ISSUE TITLE
"Update dependencies" only updates what's on screen

### ISSUE THREAD

**Issue by unional** [vscode-contrib/vscode-versionlens#43]
This also applies to "Update devDependencies".

When there are more dependencies than the screen can show, click on "Update dependencies" only update those visible.

**Comment by pflannery** [comment]
This was explained in the notes under the change log for 0.11.0 release [here](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md)

I can only fix this if and when this limitation is changed in vscode itself.
