### ISSUE TITLE
NuGet support in .csproj files

### ISSUE THREAD

**Issue by Crevil** [vscode-contrib/vscode-versionlens#44]
Would be great if this extension supported `.csproj` files with NuGet version lookups.

The format is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
  </ItemGroup>
</Project>
```

Each dependency is the `PackageReference` tag and the `Include` attribute can either be the NuGet package name or a relative path to another dotnet project.

**Comment by pflannery** [comment]
yeah that would be cool @Crevil

**Comment by eamodio** [comment]
@pflannery would you accept a PR for this? I'm thinking it would probably add a dependency like: https://github.com/Leonidas-from-XIV/node-xml2js

**Comment by pflannery** [comment]
@eamodio yes a PR would be welcome!!
