### ISSUE TITLE
Support yarn

### ISSUE THREAD

**Issue by codepunkt** [vscode-contrib/vscode-versionlens#45]
I would love to see a configuration option that allows to install updates to npm packages using [yarn](https://github.com/yarnpkg/yarn) instead of npm!

**Comment by pflannery** [comment]
This plugin only uses NPM to list the latest version of each package but it doesn't install or update the packages as this is left to the dev who can use the engine they prefer. 
Unless YARN lists different package versions compared to NPM then I don't see the need to change this plugin as it's doesn't install\update

There are some YARN plugins the allows you to run install or update from inside vscode but the built in terminal is just as easy to use too.

**Comment by codepunkt** [comment]
Nope, it doesn't. I thought it was supposed to also update them using `npm` commands which wouldn't update `yarn.lock` file.

Guess i can close this and won't have to open one that asks why updating doesn't work :-)
