### ISSUE TITLE
Add configuration to lock major version

### ISSUE THREAD

**Issue by clavecoder** [vscode-contrib/vscode-versionlens#46]
I understand why you ignore the restriction of the ^ notation in your update algorithm; however, there are cases where it would be nice for it to be respected. Example: @types/node has versions of v7.x.x but @types/node v6.x.x support NodeJS. 6.x, the LTS version, which our repo uses.

If you could configure VersionLens to respect certain version spec rules, it would be very helpful.

**Comment by pflannery** [comment]
This is a bug and it should repsect semver. 
It looks like this bug began in #17 and the tests didn't catch it.

**Comment by pflannery** [comment]
@clavecoder This issue should be resolved in [v0.12.2](https://github.com/vscode-contrib/vscode-versionlens/commit/3af7a58b6b1ac2737d1d2a40222326e8ecd68f4e). 
It wasn't #17 that caused the issue. It was just not passing ranged versions to `npm view` to restrict it's results. 
Let me know how it goes. thanks

**Comment by clavecoder** [comment]
Yup 3af7a58 fixes it! I just used it now and only suggested the patch upgrade to @types/node. Yay!

**Comment by pflannery** [comment]
awesome!
