### ISSUE TITLE
Show when locally installed deps in node_modules don't match package.json

### ISSUE THREAD

**Issue by zwacky** [vscode-contrib/vscode-versionlens#47]
e.g. lot of branch switching with new package jsons but since node_modules is gitignored, I'm not completely sure that the wanted version is also locally installed.

I was thinking about adding on the left side a "⚠️" note that it's not matching the locally installed library in node_modules. Sort of like how gitlens does it with the git blame:

![gitlens](https://raw.githubusercontent.com/eamodio/vscode-git-codelens/master/images/gitlens-preview1.gif)

**Comment by pflannery** [comment]
@zwacky Would be cool. PR's welcome :D

**Comment by pflannery** [comment]
This has been added in the upcoming [v0.16.0](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0160)

**Package install status**

![Image](https://cloud.githubusercontent.com/assets/1727302/25782781/c6352e30-3348-11e7-8cbe-f056140cce8a.png)

**When showing dist tags latest is shown**

![Image](https://cloud.githubusercontent.com/assets/1727302/25782884/46d11af8-334a-11e7-9a6d-b47e6f0f5f7d.png)


also relates with #53
