### ISSUE TITLE
Have a link to latest changelogs

### ISSUE THREAD

**Issue by zwacky** [vscode-contrib/vscode-versionlens#48]
It'd be really sweet to have next to the `⬆️ 1.2.4` another codelens with a link to the project url (mostly GitHub) itself and opening in the browser right away.
If it's a GitHub project, it could already open in the releases tab.

Would look something like: `⬆️ 1.2.4 | changelogs`

**Comment by pflannery** [comment]
@zwacky Would be cool. PR's welcome too :D
