### ISSUE TITLE
Add a toggle command

### ISSUE THREAD

**Issue by obambrough** [vscode-contrib/vscode-versionlens#51]
Add a toggle command so that Version Lens only displays its CodeLens when toggled on. This allows you to review your package.json without the jarring reflow, until you wish to see the version information.

**Comment by pflannery** [comment]
This is implemented in 0.15.0

![toggle-show-preview](https://cloud.githubusercontent.com/assets/1727302/25732846/a559db42-314b-11e7-94dd-5feb91797999.gif)

You can see the details in the [CHANGELOG](https://github.com/vscode-contrib/vscode-versionlens/blob/f7f5de5482e73a0c109509c08086929cf1e5a1bc/CHANGELOG.md)

**Comment by obambrough** [comment]
That's great, thank you!
