### ISSUE TITLE
Support F# project files (fsproj)

### ISSUE THREAD

**Issue by jp7677** [vscode-contrib/vscode-versionlens#52]
Hi there,

Since support for the new csproj format has been landed (which is btw really really cool!), could you also enable the same for F# projects? I guess from your perspective the only difference would be that the project file ends with `fsproj` instead of `csproj`. See e.g. https://github.com/jp7677/hellocoreclr/blob/master/src/HelloCoreClrApp.Rules/HelloCoreClrApp.Rules.fsproj for a simple sample.

Regards,
Jens

**Comment by pflannery** [comment]
This has been added in the upcoming [v0.16.0](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0160)

**Comment by jp7677** [comment]
Very cool, thanks a lot!
