### ISSUE TITLE
Feature request: Show latest version and currently installed version

### ISSUE THREAD

**Issue by calrsom** [vscode-contrib/vscode-versionlens#53]
Our project uses caret ranges for dependencies.  It would be nice if your extension showed:
 * Currently installed version
 * Available version through `npm update`
 * Major available version that would need to be specified

Basically, the kinds of info provided by [ncu](https://www.npmjs.com/package/npm-check-updates).  Also, see [semver](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) for a description of caret ranges.

Right now the code lens shows "matches x" where x is the currently listed version; this really isn't helpful at all, and I just shut the extension off.

**Comment by pflannery** [comment]
> Major available version that would need to be specified

Currenlty the semver library along with `npm view` is used to evaluate the specified version in the package against the latest version (or the latest version within the range specified)

For ranges like `~ or ^` it will show the latest version within the range that it will install, like:

![image](https://cloud.githubusercontent.com/assets/1727302/25768780/f2c3b3b4-3202-11e7-9c11-93c8f4de8f18.png)

![image](https://cloud.githubusercontent.com/assets/1727302/25768805/6b9ec1fc-3203-11e7-9f82-3b1d623863f7.png)

![image](https://cloud.githubusercontent.com/assets/1727302/25768847/2cccee58-3204-11e7-821d-1a2a0a97f910.png)

Were able to view the dist tags for a package but it isn't showing the 'latest' as a constant entry.

So I think to keep this minimal the solution here would be to add the 'latest' as a dist tag like:

![image](https://cloud.githubusercontent.com/assets/1727302/25769235/e9068ea6-320b-11e7-9345-c4f5602e4ae6.png)

> Currently installed version
> Available version through npm update

This is something I'm working on at the moment. The next version will show the information similar to what appears with `npm outdated`, 

I'm looking at something similar to unit test status icons which will appear to each package to indicate "installed, out of date and missing". Most likely in the form of traffic light colours.

**Comment by pflannery** [comment]
This has been added in the upcoming [v0.16.0](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0160)

**Package install statuses**

![Image](https://cloud.githubusercontent.com/assets/1727302/25782781/c6352e30-3348-11e7-8cbe-f056140cce8a.png)

**When showing dist tags latest is shown**

![Image](https://cloud.githubusercontent.com/assets/1727302/25782884/46d11af8-334a-11e7-9a6d-b47e6f0f5f7d.png)
