### ISSUE TITLE
The yellow labels are nearly unreadable...

### ISSUE THREAD

**Issue by Ritzlgrmft** [vscode-contrib/vscode-versionlens#56]
... when using the light (or light+) color scheme.

"Yellow labels" are the labels shown, when I haven't installed the newest version (e.g. `@angular/core@4.0.0`.

**Comment by pflannery** [comment]
@Ritzlgrmft 

Thanks for letting me know.
I will make them brighter by default and also make the colours configurable too

**Comment by pflannery** [comment]
This is fixed in [0.16.2](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0162)

**Comment by Ritzlgrmft** [comment]
Thanks for the fast response! The new colours are much better to read, so I do not need to change them - although it were possible now!
