### ISSUE TITLE
Enhancement: Add support for pip's requirements.txt

### ISSUE THREAD

**Issue by eMerzh** [vscode-contrib/vscode-versionlens#57]
Hi, 
the project is really great, 
it would be cool to have support for requirements files

**Comment by pflannery** [comment]
Fine by me. Would except PRs for this.

**Comment by SpectralKH** [comment]
Would love this

**Comment by SpectralKH** [comment]
@darkvertex [Poetry](https://poetry.eustace.io)'s pyproject.toml would be nice too https://poetry.eustace.io/docs/pyproject/

**Comment by pflannery** [comment]
this issue has been transfered to it's new home at gitlab.

https://gitlab.com/versionlens/vscode-versionlens/-/issues/57
