### ISSUE TITLE
Showing tagged dependencies could be overwhelming

### ISSUE THREAD

**Issue by eamodio** [vscode-contrib/vscode-versionlens#61]
While I **love** the support for tagged versions, I feel like the current code lens structure could be very overwhelming.

![image](https://cloud.githubusercontent.com/assets/641685/26013998/b27724dc-3728-11e7-8d97-67c4803b33e0.png)

As an alternative idea, what do you think of instead of rendering code lens for each tagged version and instead render a single code lens (when there was at least 1 tagged version later than the current) and then clicking on that code lens would show a quickpick to disambiguate which tagged version you wanted. It could also be a combo deal, where if there is only 1 then it just renders the single one, but if more than 1, then it falls back to a quick pick.

What do you think? Either as a replacement for the current behavior or as a customization setting?

Part of the issue could be that it seems like tagged dependencies prior to the current version are also show, rather than just newer ones. -- this might just be a separate bug

**Comment by pflannery** [comment]
Your right it's overwhelming especially for dot net.

I've made sure that tagged versions are not shown when they are older and have fixed this in [0.17.1](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0171)

A quick pick lookup is a good idea but I'm hoping to avoid it at the moment.

**Comment by eamodio** [comment]
@pflannery thanks that makes a big difference (at least for now until my version is behind a lot more). It also seems worse for .net because there really isn't a notion of "tagged" releases its just an arbitrary label tacked on to the version number -- so they may or may not group well.
