### ISSUE TITLE
Wrong latest version detected?

### ISSUE THREAD

**Issue by rfgamaral** [vscode-contrib/vscode-versionlens#67]
- [gajus/react-css-modules](https://github.com/gajus/react-css-modules)

![image](https://cloud.githubusercontent.com/assets/96476/26096893/98cd6588-3a1a-11e7-9c4d-2d6d8f0cd995.png)

![image](https://cloud.githubusercontent.com/assets/96476/26096927/b8adcef6-3a1a-11e7-9b06-239118032460.png)

Not sure if the problem is on version lens or react css modules tags.

It should display "latest installed". It's not the latest sorted by date, but it's the latest sorted by semver.

**Comment by pflannery** [comment]
@rfgamaral Thanks for reporting this.

Version lens is using `npm view` to determine the nearest version and `npm outdated` to determine whats currently installed

It gets the tags using `npm view react-css-modules dist-tags` 

This is what I saw when writing this reply using `npm view react-css-modules version`

![image](https://cloud.githubusercontent.com/assets/1727302/26103228/63769718-3a30-11e7-9450-68dd8a04a25d.png)

and  `npm view react-css-modules dist-tags` 

![image](https://cloud.githubusercontent.com/assets/1727302/26103326/d5141fc6-3a30-11e7-9f31-36b2c6d4bc78.png)

So what your seeing is correct. 

Maybe something like "4.1.0 prerelease installed" would leave us more certain in these cases.

**Comment by pflannery** [comment]
Scratch my last comment. Not sure why your seeing "4.1.0 installed" though. That maybe a bug. 
What happens when you reload the package.json in the editor?

**Comment by pflannery** [comment]
ok I now see that "4.1.0" is a valid npm version it's just not the latest version according to npm dist-tags. 

Maybe this is an npm dist-tag issue?

**Comment by rfgamaral** [comment]
I'm not exactly sure as I don't really know how that stuff works :(

**Comment by rfgamaral** [comment]
It's like NPM is looking at the latest tagged version by date and completely ignoring semver.

**Comment by rfgamaral** [comment]
If you do this:

```
npm view react-css-modules version
4.0.5
```

But this gives you:

```
[ '0.0.0',
  '0.0.1',
  '0.0.2',
  '0.1.0',
  '1.0.0',
  '1.1.0',
  '1.2.0',
  '1.3.0',
  '2.0.0',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '3.0.4',
  '3.0.5',
  '3.0.6',
  '3.1.0',
  '3.2.0',
  '3.2.1',
  '3.2.2',
  '3.2.3',
  '3.3.0',
  '3.3.1',
  '3.4.0',
  '3.5.0',
  '3.5.1',
  '3.5.2',
  '3.6.0',
  '3.6.1',
  '3.6.2',
  '3.6.3',
  '3.6.4',
  '3.6.5',
  '3.6.6',
  '3.6.7',
  '3.6.8',
  '3.7.0',
  '3.7.2',
  '3.7.3',
  '3.7.4',
  '3.7.5',
  '3.7.6',
  '3.7.7',
  '3.7.8',
  '3.7.9',
  '3.7.10',
  '4.0.0',
  '4.0.2',
  '4.0.3',
  '4.0.5',
  '4.1.0',
  '4.2.0',
  '4.2.1' ]
```

This latest one is ordered correctly.

**Comment by pflannery** [comment]
Not quite sure how that's happening but I think it's https://github.com/gajus/react-css-modules issue.

There is a related issue here https://github.com/gajus/react-css-modules/issues/238

**Comment by rfgamaral** [comment]
Yeah, I just read [this](http://jbavari.github.io/blog/2015/10/16/using-npm-tags/) and it feels like a `react-css-modules` issue. Sorry about that and thanks for your time.
