### ISSUE TITLE
Stop working if includes git+https deps

### ISSUE THREAD

**Issue by SDSLeon** [vscode-contrib/vscode-versionlens#68]
example: 
"test": "git+https://git@github.com/testuser/test.git",

**Comment by pflannery** [comment]
@SDSLeon Thanks for reporting this.

It's fixed in [pre-releases/0.18.0-beta.1](https://github.com/vscode-contrib/vscode-versionlens/releases/tag/0.18.0-beta.1)

It isn't published to vscode yet but you can try it by downling the vsix file and installing manually

**Comment by SDSLeon** [comment]
@pflannery install 0.18.0-beta.1, problem fixed, thanks!

**Comment by pflannery** [comment]
Now implemented in [0.18.0](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0180)
