### ISSUE TITLE
command 'versionlens.showVersionLenses' not found

### ISSUE THREAD

**Issue by bialad** [vscode-contrib/vscode-versionlens#69]
Since some time back versionlens is not working for me anymore. The codelens feature stopped working, and when I try to run a command using the command palette I get command not found on all options.

VS Code:
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

versionlens:
0.17.2

I don't know how to see a extension log, if that's possible.

**Comment by pflannery** [comment]
@bialad 
Sound like vscode isn't installing properly which some times happens #50 

Can you open the developer tools and see if there is an error being generated?

![image](https://cloud.githubusercontent.com/assets/1727302/26168133/f37fe840-3b30-11e7-9bcc-da83585cd556.png)

**Comment by bialad** [comment]
Actually, it loaded when I opened Developer Tools. There were now errors or warning in the console, just a console log of my installed extensions. So maybe it restarted all extension.

It also loads when I restart Code. So, problem solved?!? I guess. I'll close this since I can't reproduce it anymore.
