### ISSUE TITLE
Broken characters 

### ISSUE THREAD

**Issue by rokoroku** [vscode-contrib/vscode-versionlens#70]
VSCode version: 1.12.2
Version Lens version: 0.18.0
OS: OS X 10.12.4

![2017-05-18 9 34 37](https://cloud.githubusercontent.com/assets/5208632/26181867/a09ff65a-3bae-11e7-9050-c8703855f501.png)

As you can see, the upward arrow character is now broken and displayed as an empty rectangle.

**Comment by pflannery** [comment]
@rokoroku Thanks for reporting this. 

I don't have a mac anymore but I'm going to guess osx doesn't support these unicodes,  '⮬',  '⮮' ? 
Can you see the arrows here or is it showing squares too http://graphemica.com/%E2%AE%AC

**Comment by rokoroku** [comment]
There is no supported character on MAC after the `Unicode code point: U+1AB3` entry, from this result: http://graphemica.com/search?page=5&q=arrow.

**Comment by pflannery** [comment]
@rokoroku 
I've made an update and hopefully mac can see the arrows..
Could you install the version below manually and see if the arrows are ok?

#### Manual Install Instructions

1. Remove the existing version lens (if installed)

2. Install [vscode-versionlens-0.18.1-beta.1.zip](https://github.com/vscode-contrib/vscode-versionlens/files/1009556/vscode-versionlens-0.18.1-beta.1.zip) via the extension menu
    ![image](https://cloud.githubusercontent.com/assets/1727302/26042216/769b47b8-392b-11e7-888f-6bc947e9623d.png)

**Comment by WebFreak001** [comment]
having the same issue on linux

**Comment by rokoroku** [comment]
@pflannery Fixed in OS X 👍  
![2017-05-18 8 29 54](https://cloud.githubusercontent.com/assets/5208632/26200386/c925d02c-3c08-11e7-8525-b457efdbfbaa.png)

**Comment by WebFreak001** [comment]
still broken (on master)

**Comment by pflannery** [comment]
@WebFreak001 What linux dist are you using? I see the icons in current release are working on ubuntu. 

Can you also manually install the link in https://github.com/vscode-contrib/vscode-versionlens/issues/70#issuecomment-302279953 ? This isn't in master yet

**Comment by WebFreak001** [comment]
yeah the download from the comment fixed it

**Comment by pflannery** [comment]
@rokoroku @WebFreak001 Thanks for your help

This is fixed in [0.18.1](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0181)
