### ISSUE TITLE
Improvement Suggestions

### ISSUE THREAD

**Issue by beeing** [vscode-contrib/vscode-versionlens#71]
Hi, I like this extension which boost programmer's productivity.

I've some suggestions that hope it will benefit everyone:
- Option to hide text, just show color dots
- The update to latest link should beside the dots
- Option to hide the text `latest`, `satisfies latest`

Everyone has their own preferences, therefore making it as settings or command will be nice.

Again, thanks for the lovely extension.

**Comment by pflannery** [comment]
sounds reasonable
