### ISSUE TITLE
After editing package.json (maybe others) causes horizontal scroll position is reset

### ISSUE THREAD

**Issue by eamodio** [vscode-contrib/vscode-versionlens#72]
I'm not sure if this is VersionLens or vscode codelens rendering triggered by VersionLens, but when I'm editing long lines in my package.json (for GitLens) VersionLens seems to trigger on the change (not a save) and re-render (I see the spinner). And very often when that happens the horizontal scroll position will be reset (although the cursor stays in the same place).

I'm not sure why VersionLens is triggering on edits (rather than save), but I guess either way if it reset the scroll position it would be annoying :)

**Comment by pflannery** [comment]
It only responds to lens events. I did do a [fix](https://github.com/vscode-contrib/vscode-versionlens/commit/ea1bd4ed07722fa5f5322ce83bf62044b644c013) related but fully fixing https://github.com/vscode-contrib/vscode-versionlens/issues/66

It was something to do with the range start and end not being the same.

**Comment by pflannery** [comment]
@eamodio 

Fixed in [v0.19.0](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0190)

**Comment by eamodio** [comment]
Awesome! Works great!
