### ISSUE TITLE
support composer

### ISSUE THREAD

**Issue by jens1o** [vscode-contrib/vscode-versionlens#73]
Hi,

I like the extension, but I'm missing support for my php projects. Are you fine with that change? I can provide a pr for you if you want to.

Thanks!
Jens

**Comment by pflannery** [comment]
@jens1o 
Yes would be happy to take a PR.

**Comment by Jany-M** [comment]
I second this request!

**Comment by jens1o** [comment]
@pflannery I think feature requests shouldn't be marked as stale. :/

**Comment by Cerzat43** [comment]
I'm working on a pull request for this.
I'll have a first iteration in a few days.
