### ISSUE TITLE
Add option to show lens inline

### ISSUE THREAD

**Issue by dotlouis** [vscode-contrib/vscode-versionlens#74]
Hi, first of all it's a great and very useful extension, it's exactly what I was looking for !
It would be awesome if we could have the version lens to display inline next to the package name (to the left or to the right) because if you have a big package.json, it doubles the number of lines to scroll and makes it hard to skim over the file quickly.
Thanks for your work,
Cheers !

**Comment by pflannery** [comment]
Unfortunately this option is not available for lenses in vscode - https://github.com/Microsoft/vscode/issues/22127

**Comment by pflannery** [comment]
Relates to https://github.com/vscode-contrib/vscode-versionlens/issues/40
