### ISSUE TITLE
support private NuGet feeds

### ISSUE THREAD

**Issue by dmccaffery** [vscode-contrib/vscode-versionlens#75]
VersionLens currently only supports NuGet packages hosted on nuget.org. Many OSS projects host packages on MyGet and many enterprise organizations host their own feeds using the Package Management features of VSTS and TFS.

NuGet feeds are determined using nuget.config files stored within the project, at the user level, or system wide. Some feeds are also authenticated, as an FYI.

I'm not sure what the best solution for this would be, but it would definitely be an amazing thing to have.

**Comment by pflannery** [comment]
@dmccaffery 

Currently it's using a static URL [here](https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/providers/dotnet/nugetAPI.js#L9)
I could just make that URL configurable in the settings. Would that suffice?

**Comment by dmccaffery** [comment]
@pflannery 

sorry for not getting back to you previously -- I missed this notification in email somehow. Making the nuget feed url configurable as an array would suffice; if parsing nuget.config is out of the question short term. It does need to be an array, though, or at least always hit nuget.org in addition to whatever URL is configurable.

**Comment by SeijiSuenaga** [comment]
This would be useful for me as well.  Parsing C:/Users/username/AppData/Roaming/NuGet/NuGet.Config would be ideal, if possible.

**Comment by cilerler** [comment]
It also doesn't support local folders 😢 More details at https://github.com/vscode-contrib/vscode-versionlens/issues/98

**Comment by TomJKlug** [comment]
We would also love this added as we utilize private nuget feeds a lot.

**Comment by jrwpatterson** [comment]
any word on this it would be amazing if it was added, of it it went to the nuget targets file...

**Comment by cilerler** [comment]
go away **stale boat** 😄 this issue is important for me... 😎

**Comment by sjk07** [comment]
good job stale bot, stay away 🍻

**Comment by Svetomechc** [comment]
@Hoffs @pflannery I suggest to reopen this issue as current implementation doesn't support private nuget feeds which require authorization (then what's the whole point of a private nuget feed?). Parsing nuget.config in current workspace folder and/or default locations would be preferrable, as it usually contains Username and ClearTextPassword xml fields for accessing such private nuget feeds.

**Comment by pflannery** [comment]
1.0.0 is live now. This issue is now addressed

**Comment by pflannery** [comment]
Only v3 of the nuget api is supported at present

You can add new sources by either

  - running `dotnet nuget add {source}`. [See more here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source)
 - or by adding service index urls to `versionlens.dotnet.nuget.sources`.
