### ISSUE TITLE
Not working with latest insiders build

### ISSUE THREAD

**Issue by eamodio** [vscode-contrib/vscode-versionlens#77]
Sorry for the poor bug report (I'm currently traveling on vacation), but I was working on fixing a [GitLens issue](https://github.com/eamodio/vscode-gitlens/issues/118) with the latest insiders build and noticed that VersionLens didn't seem to be working anymore (at least for `package.json` files). I didn't notice anything in the console window, but I didn't have time (nor the code on this machine) to dig into it further (sorry).

**Comment by pflannery** [comment]
Thanks @eamodio for reporting this.

I just updated to 1.15.0-insider and seems to be working. 

Can you try re-installing?
