### ISSUE TITLE
Incorrect 'installed' versions shown

### ISSUE THREAD

**Issue by obambrough** [vscode-contrib/vscode-versionlens#78]
VS Code 1.14.2
Version Lens 0.19.1

Version lens shows the wrong version numbers for installed npm packages.

Steps to reproduce:

1. Create a package.json with a dependency defined (e.g. typescript@2.0.6)
1. npm install
1. Open VS Code and verify Version Lens shows installed version as 2.0.6 (Using 'Show dependency statuses')
1. Update package.json to specify the typescript version as ~2.3.3 (but don't perform an npm update.) Version Lens shows '2.3.4 installed' when 2.0.6 is actually installed.

**Comment by mxtopher** [comment]
It seems to have been fixed here: 27bc36efa5c5e81529d9c09179f2af23ca303fe4
I wasn't able to repro. @obambrough, Do you mind taking a look again if it works for you?

Thanks.

**Comment by obambrough** [comment]
@mxtopher Thanks for pointing that out. I can't reproduce it now either (using Version Lens 0.20.0 on VS Code 1.21.1.) - Odd that the commit you pointed out was already committed and tagged against Version Lens 0.19.1 which I noted was showing the issue.
