### ISSUE TITLE
bower: rate limit exceeded

### ISSUE THREAD

**Issue by dmccaffery** [vscode-contrib/vscode-versionlens#83]
GitHub API calls for bower end up exceeding the rate limit for GH fairly quickly. Support should be added for configuring a GitHub token used to authenticate requests, even if it comes from an environment variable.

**Comment by pflannery** [comment]
@dmccaffery Can you try setting the 'versionlens.github.accessToken'.

**Comment by dmccaffery** [comment]
works, thanks! -- my apologies for the delay In getting back to you.
