### ISSUE TITLE
Stick with old proxy settings

### ISSUE THREAD

**Issue by PavelD** [vscode-contrib/vscode-versionlens#84]
I had problem to set up the proxy for vscode. Finally it worked with the --proxy-server=.... (even if it has been set correctly in the settings before)

When i tried to connect again without the proxy server (option --no-proxy-server) including the removal from the settings the plugin still keeps old proxy settings:

Error: NPM: parseNpmArguments Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND xxxxxx:8080
	at C:\Users\xxx\.vscode\extensions\pflannery.vscode-versionlens-0.19.1\out\extension-bundle.js:1246:19
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:109:7)

Restart and even reinstall does not help.

The rest of the vscode is working without proxy well.

**Comment by pflannery** [comment]
This extension doesnt interact with the proxy settings of vscode.

Is there a proxy set in your NPM config? https://docs.npmjs.com/misc/config#proxy **or** https://docs.npmjs.com/misc/config#https-proxy

**Comment by PavelD** [comment]
OK, good to know...

**Comment by PavelD** [comment]
OK, good to know...
