### ISSUE TITLE
didn't read globalconfig

### ISSUE THREAD

**Issue by unional** [vscode-contrib/vscode-versionlens#90]
I notice config in globalconfig (e.g. `C:\Proram Files\nodejs\etc\npmrc`) is not read, only userconfig (`C:\Users\<user>\.npmrc`) is read.

This cause some of my scoped package not able to see the versions because my scoped package registry mapping is defined in the globalconfig instead of userconfig (because this is a machine shared by multiple developers).

e.g.
```sh
# globalconfig
@abc:registry="http://private.cloud.local/npm-registry"
```

**Comment by pflannery** [comment]
duplicate of #38
