### ISSUE TITLE
Optionally show package version information on the right

### ISSUE THREAD

**Issue by kachkaev** [vscode-contrib/vscode-versionlens#92]
It'd be great if there was an option to see package versions on the right, similar to what [`import-cost`](https://github.com/wix/import-cost) and [`gitlens`](https://github.com/eamodio/vscode-gitlens) are doing. This way `package.json` does not stretch and it therefore becomes easier to glance through the outdated packages.

`import-cost` and `gitlens` do not have major problems working together despite that they are competing for the same space. `import-cost` simply prevents `gitlens` info to be shown when a cursor is moved to a line with the `import-cost` info. `versionlens` could play the same way as `import-cost` does.

<img width="746" alt="screen shot 2018-02-09 at 12 43 45" src="https://user-images.githubusercontent.com/608862/36028593-8a780848-0d97-11e8-9a55-4866037fc5d5.png">

---

<img width="485" alt="screen shot 2018-02-09 at 12 47 25" src="https://user-images.githubusercontent.com/608862/36028596-8d3cbb96-0d97-11e8-96de-b369e7472372.png">

**Comment by pflannery** [comment]
This was discussed in a previous issue #40 

As [mentioned in the comments of #40](https://github.com/vscode-contrib/vscode-versionlens/issues/40#issuecomment-298991913) until MS reopens [this](https://github.com/Microsoft/vscode/issues/22127) then we cant do implement.

**Comment by kachkaev** [comment]
Ah, true. Sorry for not being able to find #40 and creating a duplicate! Completely understand what's blocking this now.
