### ISSUE TITLE
Doesn't seem to work on package.json

### ISSUE THREAD

**Issue by Mohamed3on** [vscode-contrib/vscode-versionlens#93]
I've installed the extension, reloaded the editor, opened `package.json`, and didn't see any changes:
![image](https://user-images.githubusercontent.com/12295159/36036582-888b5760-0dba-11e8-9ce7-22491d22405c.png)
I've tried with a couple of projects, same output.
What am I doing wrong?

**Comment by Mohamed3on** [comment]
Never mind, I had VSCode use "language mode: JSONC" with JSON to allow comments in JSON, but it doesn't seem to work with this extension. Reverting it to JSON works.

**Comment by mattgaspar** [comment]
I had this problem as well.  Installed the extension a few weeks ago and thought it was broken.  Finally got around to looking at github.  Can you add support for JSON with comments?  Or at least put a note in the readme!
